package com.car.bean;


public class Car {

    private String carid;
    private String brand;
    private String name;
    private String type;
    private String energyresource;
    private String detail;
    private String purl;
    private String purl1;
    private String purl2;
    private String purl3;
    private String purl4;
    public String getCarid() {
        return carid;
    }
    public void setCarid(String carid) {
        this.carid = carid == null ? null : carid.trim();
    }
    public String getBrand() {
        return brand;
    }
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
    public String getType() {
        return type;
    }
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.EnergyResource
     *
     * @return the value of car.EnergyResource
     *
     * @mbg.generated
     */
    public String getEnergyresource() {
        return energyresource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.EnergyResource
     *
     * @param energyresource the value for car.EnergyResource
     *
     * @mbg.generated
     */
    public void setEnergyresource(String energyresource) {
        this.energyresource = energyresource == null ? null : energyresource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.detail
     *
     * @return the value of car.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.detail
     *
     * @param detail the value for car.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.Purl
     *
     * @return the value of car.Purl
     *
     * @mbg.generated
     */
    public String getPurl() {
        return purl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.Purl
     *
     * @param purl the value for car.Purl
     *
     * @mbg.generated
     */
    public void setPurl(String purl) {
        this.purl = purl == null ? null : purl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.Purl1
     *
     * @return the value of car.Purl1
     *
     * @mbg.generated
     */
    public String getPurl1() {
        return purl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.Purl1
     *
     * @param purl1 the value for car.Purl1
     *
     * @mbg.generated
     */
    public void setPurl1(String purl1) {
        this.purl1 = purl1 == null ? null : purl1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.Purl2
     *
     * @return the value of car.Purl2
     *
     * @mbg.generated
     */
    public String getPurl2() {
        return purl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.Purl2
     *
     * @param purl2 the value for car.Purl2
     *
     * @mbg.generated
     */
    public void setPurl2(String purl2) {
        this.purl2 = purl2 == null ? null : purl2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.Purl3
     *
     * @return the value of car.Purl3
     *
     * @mbg.generated
     */
    public String getPurl3() {
        return purl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.Purl3
     *
     * @param purl3 the value for car.Purl3
     *
     * @mbg.generated
     */
    public void setPurl3(String purl3) {
        this.purl3 = purl3 == null ? null : purl3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.Purl4
     *
     * @return the value of car.Purl4
     *
     * @mbg.generated
     */
    public String getPurl4() {
        return purl4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.Purl4
     *
     * @param purl4 the value for car.Purl4
     *
     * @mbg.generated
     */
    public void setPurl4(String purl4) {
        this.purl4 = purl4 == null ? null : purl4.trim();
    }
}