package com.forum.model.entity;

public class Ac_refrigerator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_refrigerator.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_refrigerator.AirConditioningControlMode
     *
     * @mbg.generated
     */
    private String airconditioningcontrolmode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_refrigerator.RearIndependentAirConditioning
     *
     * @mbg.generated
     */
    private String rearindependentairconditioning;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_refrigerator.RearSeatHVACDucts
     *
     * @mbg.generated
     */
    private String rearseathvacducts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_refrigerator.TemperatureZoningControl
     *
     * @mbg.generated
     */
    private String temperaturezoningcontrol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_refrigerator.In_carAirConditioning_Pollenfiltration
     *
     * @mbg.generated
     */
    private String inCarairconditioningPollenfiltration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_refrigerator.CarRefrigerator
     *
     * @mbg.generated
     */
    private String carrefrigerator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_refrigerator.Num
     *
     * @return the value of ac_refrigerator.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_refrigerator.Num
     *
     * @param num the value for ac_refrigerator.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_refrigerator.AirConditioningControlMode
     *
     * @return the value of ac_refrigerator.AirConditioningControlMode
     *
     * @mbg.generated
     */
    public String getAirconditioningcontrolmode() {
        return airconditioningcontrolmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_refrigerator.AirConditioningControlMode
     *
     * @param airconditioningcontrolmode the value for ac_refrigerator.AirConditioningControlMode
     *
     * @mbg.generated
     */
    public void setAirconditioningcontrolmode(String airconditioningcontrolmode) {
        this.airconditioningcontrolmode = airconditioningcontrolmode == null ? null : airconditioningcontrolmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_refrigerator.RearIndependentAirConditioning
     *
     * @return the value of ac_refrigerator.RearIndependentAirConditioning
     *
     * @mbg.generated
     */
    public String getRearindependentairconditioning() {
        return rearindependentairconditioning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_refrigerator.RearIndependentAirConditioning
     *
     * @param rearindependentairconditioning the value for ac_refrigerator.RearIndependentAirConditioning
     *
     * @mbg.generated
     */
    public void setRearindependentairconditioning(String rearindependentairconditioning) {
        this.rearindependentairconditioning = rearindependentairconditioning == null ? null : rearindependentairconditioning.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_refrigerator.RearSeatHVACDucts
     *
     * @return the value of ac_refrigerator.RearSeatHVACDucts
     *
     * @mbg.generated
     */
    public String getRearseathvacducts() {
        return rearseathvacducts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_refrigerator.RearSeatHVACDucts
     *
     * @param rearseathvacducts the value for ac_refrigerator.RearSeatHVACDucts
     *
     * @mbg.generated
     */
    public void setRearseathvacducts(String rearseathvacducts) {
        this.rearseathvacducts = rearseathvacducts == null ? null : rearseathvacducts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_refrigerator.TemperatureZoningControl
     *
     * @return the value of ac_refrigerator.TemperatureZoningControl
     *
     * @mbg.generated
     */
    public String getTemperaturezoningcontrol() {
        return temperaturezoningcontrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_refrigerator.TemperatureZoningControl
     *
     * @param temperaturezoningcontrol the value for ac_refrigerator.TemperatureZoningControl
     *
     * @mbg.generated
     */
    public void setTemperaturezoningcontrol(String temperaturezoningcontrol) {
        this.temperaturezoningcontrol = temperaturezoningcontrol == null ? null : temperaturezoningcontrol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_refrigerator.In_carAirConditioning_Pollenfiltration
     *
     * @return the value of ac_refrigerator.In_carAirConditioning_Pollenfiltration
     *
     * @mbg.generated
     */
    public String getInCarairconditioningPollenfiltration() {
        return inCarairconditioningPollenfiltration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_refrigerator.In_carAirConditioning_Pollenfiltration
     *
     * @param inCarairconditioningPollenfiltration the value for ac_refrigerator.In_carAirConditioning_Pollenfiltration
     *
     * @mbg.generated
     */
    public void setInCarairconditioningPollenfiltration(String inCarairconditioningPollenfiltration) {
        this.inCarairconditioningPollenfiltration = inCarairconditioningPollenfiltration == null ? null : inCarairconditioningPollenfiltration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_refrigerator.CarRefrigerator
     *
     * @return the value of ac_refrigerator.CarRefrigerator
     *
     * @mbg.generated
     */
    public String getCarrefrigerator() {
        return carrefrigerator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_refrigerator.CarRefrigerator
     *
     * @param carrefrigerator the value for ac_refrigerator.CarRefrigerator
     *
     * @mbg.generated
     */
    public void setCarrefrigerator(String carrefrigerator) {
        this.carrefrigerator = carrefrigerator == null ? null : carrefrigerator.trim();
    }
}