package com.forum.model.entity;

public class Basic_parameter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.ModelName
     *
     * @mbg.generated
     */
    private String modelname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.Price
     *
     * @mbg.generated
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.Manufacturer
     *
     * @mbg.generated
     */
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.level
     *
     * @mbg.generated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.Engine
     *
     * @mbg.generated
     */
    private String engine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.Transmission
     *
     * @mbg.generated
     */
    private String transmission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.LengthWidthHeight
     *
     * @mbg.generated
     */
    private String lengthwidthheight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.BodyStructure
     *
     * @mbg.generated
     */
    private String bodystructure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.TopSpeed
     *
     * @mbg.generated
     */
    private String topspeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.Official0-100Acceleration
     *
     * @mbg.generated
     */
    private String official0100acceleration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.Measured0-100Acceleration
     *
     * @mbg.generated
     */
    private String measured0100acceleration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.Measuredbraking100-0
     *
     * @mbg.generated
     */
    private String measuredbraking1000;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.MeasuredFuelConsumption
     *
     * @mbg.generated
     */
    private String measuredfuelconsumption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.MinistryOfIndustry
     *
     * @mbg.generated
     */
    private String ministryofindustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.MeasuredGroundClearance
     *
     * @mbg.generated
     */
    private String measuredgroundclearance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_parameter.TheVehicleWarranty
     *
     * @mbg.generated
     */
    private String thevehiclewarranty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.Num
     *
     * @return the value of basic_parameter.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.Num
     *
     * @param num the value for basic_parameter.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.ModelName
     *
     * @return the value of basic_parameter.ModelName
     *
     * @mbg.generated
     */
    public String getModelname() {
        return modelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.ModelName
     *
     * @param modelname the value for basic_parameter.ModelName
     *
     * @mbg.generated
     */
    public void setModelname(String modelname) {
        this.modelname = modelname == null ? null : modelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.Price
     *
     * @return the value of basic_parameter.Price
     *
     * @mbg.generated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.Price
     *
     * @param price the value for basic_parameter.Price
     *
     * @mbg.generated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.Manufacturer
     *
     * @return the value of basic_parameter.Manufacturer
     *
     * @mbg.generated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.Manufacturer
     *
     * @param manufacturer the value for basic_parameter.Manufacturer
     *
     * @mbg.generated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.level
     *
     * @return the value of basic_parameter.level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.level
     *
     * @param level the value for basic_parameter.level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.Engine
     *
     * @return the value of basic_parameter.Engine
     *
     * @mbg.generated
     */
    public String getEngine() {
        return engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.Engine
     *
     * @param engine the value for basic_parameter.Engine
     *
     * @mbg.generated
     */
    public void setEngine(String engine) {
        this.engine = engine == null ? null : engine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.Transmission
     *
     * @return the value of basic_parameter.Transmission
     *
     * @mbg.generated
     */
    public String getTransmission() {
        return transmission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.Transmission
     *
     * @param transmission the value for basic_parameter.Transmission
     *
     * @mbg.generated
     */
    public void setTransmission(String transmission) {
        this.transmission = transmission == null ? null : transmission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.LengthWidthHeight
     *
     * @return the value of basic_parameter.LengthWidthHeight
     *
     * @mbg.generated
     */
    public String getLengthwidthheight() {
        return lengthwidthheight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.LengthWidthHeight
     *
     * @param lengthwidthheight the value for basic_parameter.LengthWidthHeight
     *
     * @mbg.generated
     */
    public void setLengthwidthheight(String lengthwidthheight) {
        this.lengthwidthheight = lengthwidthheight == null ? null : lengthwidthheight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.BodyStructure
     *
     * @return the value of basic_parameter.BodyStructure
     *
     * @mbg.generated
     */
    public String getBodystructure() {
        return bodystructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.BodyStructure
     *
     * @param bodystructure the value for basic_parameter.BodyStructure
     *
     * @mbg.generated
     */
    public void setBodystructure(String bodystructure) {
        this.bodystructure = bodystructure == null ? null : bodystructure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.TopSpeed
     *
     * @return the value of basic_parameter.TopSpeed
     *
     * @mbg.generated
     */
    public String getTopspeed() {
        return topspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.TopSpeed
     *
     * @param topspeed the value for basic_parameter.TopSpeed
     *
     * @mbg.generated
     */
    public void setTopspeed(String topspeed) {
        this.topspeed = topspeed == null ? null : topspeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.Official0-100Acceleration
     *
     * @return the value of basic_parameter.Official0-100Acceleration
     *
     * @mbg.generated
     */
    public String getOfficial0100acceleration() {
        return official0100acceleration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.Official0-100Acceleration
     *
     * @param official0100acceleration the value for basic_parameter.Official0-100Acceleration
     *
     * @mbg.generated
     */
    public void setOfficial0100acceleration(String official0100acceleration) {
        this.official0100acceleration = official0100acceleration == null ? null : official0100acceleration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.Measured0-100Acceleration
     *
     * @return the value of basic_parameter.Measured0-100Acceleration
     *
     * @mbg.generated
     */
    public String getMeasured0100acceleration() {
        return measured0100acceleration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.Measured0-100Acceleration
     *
     * @param measured0100acceleration the value for basic_parameter.Measured0-100Acceleration
     *
     * @mbg.generated
     */
    public void setMeasured0100acceleration(String measured0100acceleration) {
        this.measured0100acceleration = measured0100acceleration == null ? null : measured0100acceleration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.Measuredbraking100-0
     *
     * @return the value of basic_parameter.Measuredbraking100-0
     *
     * @mbg.generated
     */
    public String getMeasuredbraking1000() {
        return measuredbraking1000;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.Measuredbraking100-0
     *
     * @param measuredbraking1000 the value for basic_parameter.Measuredbraking100-0
     *
     * @mbg.generated
     */
    public void setMeasuredbraking1000(String measuredbraking1000) {
        this.measuredbraking1000 = measuredbraking1000 == null ? null : measuredbraking1000.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.MeasuredFuelConsumption
     *
     * @return the value of basic_parameter.MeasuredFuelConsumption
     *
     * @mbg.generated
     */
    public String getMeasuredfuelconsumption() {
        return measuredfuelconsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.MeasuredFuelConsumption
     *
     * @param measuredfuelconsumption the value for basic_parameter.MeasuredFuelConsumption
     *
     * @mbg.generated
     */
    public void setMeasuredfuelconsumption(String measuredfuelconsumption) {
        this.measuredfuelconsumption = measuredfuelconsumption == null ? null : measuredfuelconsumption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.MinistryOfIndustry
     *
     * @return the value of basic_parameter.MinistryOfIndustry
     *
     * @mbg.generated
     */
    public String getMinistryofindustry() {
        return ministryofindustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.MinistryOfIndustry
     *
     * @param ministryofindustry the value for basic_parameter.MinistryOfIndustry
     *
     * @mbg.generated
     */
    public void setMinistryofindustry(String ministryofindustry) {
        this.ministryofindustry = ministryofindustry == null ? null : ministryofindustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.MeasuredGroundClearance
     *
     * @return the value of basic_parameter.MeasuredGroundClearance
     *
     * @mbg.generated
     */
    public String getMeasuredgroundclearance() {
        return measuredgroundclearance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.MeasuredGroundClearance
     *
     * @param measuredgroundclearance the value for basic_parameter.MeasuredGroundClearance
     *
     * @mbg.generated
     */
    public void setMeasuredgroundclearance(String measuredgroundclearance) {
        this.measuredgroundclearance = measuredgroundclearance == null ? null : measuredgroundclearance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_parameter.TheVehicleWarranty
     *
     * @return the value of basic_parameter.TheVehicleWarranty
     *
     * @mbg.generated
     */
    public String getThevehiclewarranty() {
        return thevehiclewarranty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_parameter.TheVehicleWarranty
     *
     * @param thevehiclewarranty the value for basic_parameter.TheVehicleWarranty
     *
     * @mbg.generated
     */
    public void setThevehiclewarranty(String thevehiclewarranty) {
        this.thevehiclewarranty = thevehiclewarranty == null ? null : thevehiclewarranty.trim();
    }
}