package com.forum.model.entity;

public class Body {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.length
     *
     * @mbg.generated
     */
    private String length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.width
     *
     * @mbg.generated
     */
    private String width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.height
     *
     * @mbg.generated
     */
    private String height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.Wheelbase
     *
     * @mbg.generated
     */
    private String wheelbase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.FrontWheelTrack
     *
     * @mbg.generated
     */
    private String frontwheeltrack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.BackWheelTrack
     *
     * @mbg.generated
     */
    private String backwheeltrack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.MinimumGroundClearance
     *
     * @mbg.generated
     */
    private String minimumgroundclearance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.CurbWeight
     *
     * @mbg.generated
     */
    private String curbweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.BodyStructure
     *
     * @mbg.generated
     */
    private String bodystructure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.NumberOfDoor
     *
     * @mbg.generated
     */
    private String numberofdoor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.NumberOfSeat
     *
     * @mbg.generated
     */
    private String numberofseat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.TankVolume
     *
     * @mbg.generated
     */
    private String tankvolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column body.TrunkVolume
     *
     * @mbg.generated
     */
    private String trunkvolume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.Num
     *
     * @return the value of body.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.Num
     *
     * @param num the value for body.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.length
     *
     * @return the value of body.length
     *
     * @mbg.generated
     */
    public String getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.length
     *
     * @param length the value for body.length
     *
     * @mbg.generated
     */
    public void setLength(String length) {
        this.length = length == null ? null : length.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.width
     *
     * @return the value of body.width
     *
     * @mbg.generated
     */
    public String getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.width
     *
     * @param width the value for body.width
     *
     * @mbg.generated
     */
    public void setWidth(String width) {
        this.width = width == null ? null : width.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.height
     *
     * @return the value of body.height
     *
     * @mbg.generated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.height
     *
     * @param height the value for body.height
     *
     * @mbg.generated
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.Wheelbase
     *
     * @return the value of body.Wheelbase
     *
     * @mbg.generated
     */
    public String getWheelbase() {
        return wheelbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.Wheelbase
     *
     * @param wheelbase the value for body.Wheelbase
     *
     * @mbg.generated
     */
    public void setWheelbase(String wheelbase) {
        this.wheelbase = wheelbase == null ? null : wheelbase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.FrontWheelTrack
     *
     * @return the value of body.FrontWheelTrack
     *
     * @mbg.generated
     */
    public String getFrontwheeltrack() {
        return frontwheeltrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.FrontWheelTrack
     *
     * @param frontwheeltrack the value for body.FrontWheelTrack
     *
     * @mbg.generated
     */
    public void setFrontwheeltrack(String frontwheeltrack) {
        this.frontwheeltrack = frontwheeltrack == null ? null : frontwheeltrack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.BackWheelTrack
     *
     * @return the value of body.BackWheelTrack
     *
     * @mbg.generated
     */
    public String getBackwheeltrack() {
        return backwheeltrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.BackWheelTrack
     *
     * @param backwheeltrack the value for body.BackWheelTrack
     *
     * @mbg.generated
     */
    public void setBackwheeltrack(String backwheeltrack) {
        this.backwheeltrack = backwheeltrack == null ? null : backwheeltrack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.MinimumGroundClearance
     *
     * @return the value of body.MinimumGroundClearance
     *
     * @mbg.generated
     */
    public String getMinimumgroundclearance() {
        return minimumgroundclearance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.MinimumGroundClearance
     *
     * @param minimumgroundclearance the value for body.MinimumGroundClearance
     *
     * @mbg.generated
     */
    public void setMinimumgroundclearance(String minimumgroundclearance) {
        this.minimumgroundclearance = minimumgroundclearance == null ? null : minimumgroundclearance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.CurbWeight
     *
     * @return the value of body.CurbWeight
     *
     * @mbg.generated
     */
    public String getCurbweight() {
        return curbweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.CurbWeight
     *
     * @param curbweight the value for body.CurbWeight
     *
     * @mbg.generated
     */
    public void setCurbweight(String curbweight) {
        this.curbweight = curbweight == null ? null : curbweight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.BodyStructure
     *
     * @return the value of body.BodyStructure
     *
     * @mbg.generated
     */
    public String getBodystructure() {
        return bodystructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.BodyStructure
     *
     * @param bodystructure the value for body.BodyStructure
     *
     * @mbg.generated
     */
    public void setBodystructure(String bodystructure) {
        this.bodystructure = bodystructure == null ? null : bodystructure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.NumberOfDoor
     *
     * @return the value of body.NumberOfDoor
     *
     * @mbg.generated
     */
    public String getNumberofdoor() {
        return numberofdoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.NumberOfDoor
     *
     * @param numberofdoor the value for body.NumberOfDoor
     *
     * @mbg.generated
     */
    public void setNumberofdoor(String numberofdoor) {
        this.numberofdoor = numberofdoor == null ? null : numberofdoor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.NumberOfSeat
     *
     * @return the value of body.NumberOfSeat
     *
     * @mbg.generated
     */
    public String getNumberofseat() {
        return numberofseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.NumberOfSeat
     *
     * @param numberofseat the value for body.NumberOfSeat
     *
     * @mbg.generated
     */
    public void setNumberofseat(String numberofseat) {
        this.numberofseat = numberofseat == null ? null : numberofseat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.TankVolume
     *
     * @return the value of body.TankVolume
     *
     * @mbg.generated
     */
    public String getTankvolume() {
        return tankvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.TankVolume
     *
     * @param tankvolume the value for body.TankVolume
     *
     * @mbg.generated
     */
    public void setTankvolume(String tankvolume) {
        this.tankvolume = tankvolume == null ? null : tankvolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column body.TrunkVolume
     *
     * @return the value of body.TrunkVolume
     *
     * @mbg.generated
     */
    public String getTrunkvolume() {
        return trunkvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column body.TrunkVolume
     *
     * @param trunkvolume the value for body.TrunkVolume
     *
     * @mbg.generated
     */
    public void setTrunkvolume(String trunkvolume) {
        this.trunkvolume = trunkvolume == null ? null : trunkvolume.trim();
    }
}