package com.forum.model.entity;

public class Brand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.BramdId
     *
     * @mbg.generated
     */
    private String bramdid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.BrandName
     *
     * @mbg.generated
     */
    private String brandname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.BrandLogo
     *
     * @mbg.generated
     */
    private String brandlogo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.BramdId
     *
     * @return the value of brand.BramdId
     *
     * @mbg.generated
     */
    public String getBramdid() {
        return bramdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.BramdId
     *
     * @param bramdid the value for brand.BramdId
     *
     * @mbg.generated
     */
    public void setBramdid(String bramdid) {
        this.bramdid = bramdid == null ? null : bramdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.BrandName
     *
     * @return the value of brand.BrandName
     *
     * @mbg.generated
     */
    public String getBrandname() {
        return brandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.BrandName
     *
     * @param brandname the value for brand.BrandName
     *
     * @mbg.generated
     */
    public void setBrandname(String brandname) {
        this.brandname = brandname == null ? null : brandname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.BrandLogo
     *
     * @return the value of brand.BrandLogo
     *
     * @mbg.generated
     */
    public String getBrandlogo() {
        return brandlogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.BrandLogo
     *
     * @param brandlogo the value for brand.BrandLogo
     *
     * @mbg.generated
     */
    public void setBrandlogo(String brandlogo) {
        this.brandlogo = brandlogo == null ? null : brandlogo.trim();
    }
}