package com.forum.model.entity;

public class Chassis_steering {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis_steering.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis_steering.DriveModel
     *
     * @mbg.generated
     */
    private String drivemodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis_steering.FrontSuspensionType
     *
     * @mbg.generated
     */
    private String frontsuspensiontype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis_steering.RearSuspensionType
     *
     * @mbg.generated
     */
    private String rearsuspensiontype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis_steering.PowerType
     *
     * @mbg.generated
     */
    private String powertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chassis_steering.CarBodyStructure
     *
     * @mbg.generated
     */
    private String carbodystructure;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis_steering.Num
     *
     * @return the value of chassis_steering.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis_steering.Num
     *
     * @param num the value for chassis_steering.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis_steering.DriveModel
     *
     * @return the value of chassis_steering.DriveModel
     *
     * @mbg.generated
     */
    public String getDrivemodel() {
        return drivemodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis_steering.DriveModel
     *
     * @param drivemodel the value for chassis_steering.DriveModel
     *
     * @mbg.generated
     */
    public void setDrivemodel(String drivemodel) {
        this.drivemodel = drivemodel == null ? null : drivemodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis_steering.FrontSuspensionType
     *
     * @return the value of chassis_steering.FrontSuspensionType
     *
     * @mbg.generated
     */
    public String getFrontsuspensiontype() {
        return frontsuspensiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis_steering.FrontSuspensionType
     *
     * @param frontsuspensiontype the value for chassis_steering.FrontSuspensionType
     *
     * @mbg.generated
     */
    public void setFrontsuspensiontype(String frontsuspensiontype) {
        this.frontsuspensiontype = frontsuspensiontype == null ? null : frontsuspensiontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis_steering.RearSuspensionType
     *
     * @return the value of chassis_steering.RearSuspensionType
     *
     * @mbg.generated
     */
    public String getRearsuspensiontype() {
        return rearsuspensiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis_steering.RearSuspensionType
     *
     * @param rearsuspensiontype the value for chassis_steering.RearSuspensionType
     *
     * @mbg.generated
     */
    public void setRearsuspensiontype(String rearsuspensiontype) {
        this.rearsuspensiontype = rearsuspensiontype == null ? null : rearsuspensiontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis_steering.PowerType
     *
     * @return the value of chassis_steering.PowerType
     *
     * @mbg.generated
     */
    public String getPowertype() {
        return powertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis_steering.PowerType
     *
     * @param powertype the value for chassis_steering.PowerType
     *
     * @mbg.generated
     */
    public void setPowertype(String powertype) {
        this.powertype = powertype == null ? null : powertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chassis_steering.CarBodyStructure
     *
     * @return the value of chassis_steering.CarBodyStructure
     *
     * @mbg.generated
     */
    public String getCarbodystructure() {
        return carbodystructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chassis_steering.CarBodyStructure
     *
     * @param carbodystructure the value for chassis_steering.CarBodyStructure
     *
     * @mbg.generated
     */
    public void setCarbodystructure(String carbodystructure) {
        this.carbodystructure = carbodystructure == null ? null : carbodystructure.trim();
    }
}