package com.forum.model.entity;

public class Control_configuration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.ABS
     *
     * @mbg.generated
     */
    private String abs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.EBD_CBC
     *
     * @mbg.generated
     */
    private String ebdCbc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.EBA_BAS_BA
     *
     * @mbg.generated
     */
    private String ebaBasBa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.ASR_TCS_TRC
     *
     * @mbg.generated
     */
    private String asrTcsTrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.HillAuxiliary
     *
     * @mbg.generated
     */
    private String hillauxiliary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.AutomaticParking
     *
     * @mbg.generated
     */
    private String automaticparking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.HDC
     *
     * @mbg.generated
     */
    private String hdc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.VariableSuspension
     *
     * @mbg.generated
     */
    private String variablesuspension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.AirSuspension
     *
     * @mbg.generated
     */
    private String airsuspension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.VariableSteeringRatio
     *
     * @mbg.generated
     */
    private String variablesteeringratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.FrontAxleLimitedSlipDifferential_differentialLock
     *
     * @mbg.generated
     */
    private String frontaxlelimitedslipdifferentialDifferentiallock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.CentralDifferentialLockingFunction
     *
     * @mbg.generated
     */
    private String centraldifferentiallockingfunction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_configuration.RearAxleLimitedSlipDifferential_differentialLock
     *
     * @mbg.generated
     */
    private String rearaxlelimitedslipdifferentialDifferentiallock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.Num
     *
     * @return the value of control_configuration.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.Num
     *
     * @param num the value for control_configuration.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.ABS
     *
     * @return the value of control_configuration.ABS
     *
     * @mbg.generated
     */
    public String getAbs() {
        return abs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.ABS
     *
     * @param abs the value for control_configuration.ABS
     *
     * @mbg.generated
     */
    public void setAbs(String abs) {
        this.abs = abs == null ? null : abs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.EBD_CBC
     *
     * @return the value of control_configuration.EBD_CBC
     *
     * @mbg.generated
     */
    public String getEbdCbc() {
        return ebdCbc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.EBD_CBC
     *
     * @param ebdCbc the value for control_configuration.EBD_CBC
     *
     * @mbg.generated
     */
    public void setEbdCbc(String ebdCbc) {
        this.ebdCbc = ebdCbc == null ? null : ebdCbc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.EBA_BAS_BA
     *
     * @return the value of control_configuration.EBA_BAS_BA
     *
     * @mbg.generated
     */
    public String getEbaBasBa() {
        return ebaBasBa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.EBA_BAS_BA
     *
     * @param ebaBasBa the value for control_configuration.EBA_BAS_BA
     *
     * @mbg.generated
     */
    public void setEbaBasBa(String ebaBasBa) {
        this.ebaBasBa = ebaBasBa == null ? null : ebaBasBa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.ASR_TCS_TRC
     *
     * @return the value of control_configuration.ASR_TCS_TRC
     *
     * @mbg.generated
     */
    public String getAsrTcsTrc() {
        return asrTcsTrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.ASR_TCS_TRC
     *
     * @param asrTcsTrc the value for control_configuration.ASR_TCS_TRC
     *
     * @mbg.generated
     */
    public void setAsrTcsTrc(String asrTcsTrc) {
        this.asrTcsTrc = asrTcsTrc == null ? null : asrTcsTrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.HillAuxiliary
     *
     * @return the value of control_configuration.HillAuxiliary
     *
     * @mbg.generated
     */
    public String getHillauxiliary() {
        return hillauxiliary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.HillAuxiliary
     *
     * @param hillauxiliary the value for control_configuration.HillAuxiliary
     *
     * @mbg.generated
     */
    public void setHillauxiliary(String hillauxiliary) {
        this.hillauxiliary = hillauxiliary == null ? null : hillauxiliary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.AutomaticParking
     *
     * @return the value of control_configuration.AutomaticParking
     *
     * @mbg.generated
     */
    public String getAutomaticparking() {
        return automaticparking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.AutomaticParking
     *
     * @param automaticparking the value for control_configuration.AutomaticParking
     *
     * @mbg.generated
     */
    public void setAutomaticparking(String automaticparking) {
        this.automaticparking = automaticparking == null ? null : automaticparking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.HDC
     *
     * @return the value of control_configuration.HDC
     *
     * @mbg.generated
     */
    public String getHdc() {
        return hdc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.HDC
     *
     * @param hdc the value for control_configuration.HDC
     *
     * @mbg.generated
     */
    public void setHdc(String hdc) {
        this.hdc = hdc == null ? null : hdc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.VariableSuspension
     *
     * @return the value of control_configuration.VariableSuspension
     *
     * @mbg.generated
     */
    public String getVariablesuspension() {
        return variablesuspension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.VariableSuspension
     *
     * @param variablesuspension the value for control_configuration.VariableSuspension
     *
     * @mbg.generated
     */
    public void setVariablesuspension(String variablesuspension) {
        this.variablesuspension = variablesuspension == null ? null : variablesuspension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.AirSuspension
     *
     * @return the value of control_configuration.AirSuspension
     *
     * @mbg.generated
     */
    public String getAirsuspension() {
        return airsuspension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.AirSuspension
     *
     * @param airsuspension the value for control_configuration.AirSuspension
     *
     * @mbg.generated
     */
    public void setAirsuspension(String airsuspension) {
        this.airsuspension = airsuspension == null ? null : airsuspension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.VariableSteeringRatio
     *
     * @return the value of control_configuration.VariableSteeringRatio
     *
     * @mbg.generated
     */
    public String getVariablesteeringratio() {
        return variablesteeringratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.VariableSteeringRatio
     *
     * @param variablesteeringratio the value for control_configuration.VariableSteeringRatio
     *
     * @mbg.generated
     */
    public void setVariablesteeringratio(String variablesteeringratio) {
        this.variablesteeringratio = variablesteeringratio == null ? null : variablesteeringratio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.FrontAxleLimitedSlipDifferential_differentialLock
     *
     * @return the value of control_configuration.FrontAxleLimitedSlipDifferential_differentialLock
     *
     * @mbg.generated
     */
    public String getFrontaxlelimitedslipdifferentialDifferentiallock() {
        return frontaxlelimitedslipdifferentialDifferentiallock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.FrontAxleLimitedSlipDifferential_differentialLock
     *
     * @param frontaxlelimitedslipdifferentialDifferentiallock the value for control_configuration.FrontAxleLimitedSlipDifferential_differentialLock
     *
     * @mbg.generated
     */
    public void setFrontaxlelimitedslipdifferentialDifferentiallock(String frontaxlelimitedslipdifferentialDifferentiallock) {
        this.frontaxlelimitedslipdifferentialDifferentiallock = frontaxlelimitedslipdifferentialDifferentiallock == null ? null : frontaxlelimitedslipdifferentialDifferentiallock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.CentralDifferentialLockingFunction
     *
     * @return the value of control_configuration.CentralDifferentialLockingFunction
     *
     * @mbg.generated
     */
    public String getCentraldifferentiallockingfunction() {
        return centraldifferentiallockingfunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.CentralDifferentialLockingFunction
     *
     * @param centraldifferentiallockingfunction the value for control_configuration.CentralDifferentialLockingFunction
     *
     * @mbg.generated
     */
    public void setCentraldifferentiallockingfunction(String centraldifferentiallockingfunction) {
        this.centraldifferentiallockingfunction = centraldifferentiallockingfunction == null ? null : centraldifferentiallockingfunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_configuration.RearAxleLimitedSlipDifferential_differentialLock
     *
     * @return the value of control_configuration.RearAxleLimitedSlipDifferential_differentialLock
     *
     * @mbg.generated
     */
    public String getRearaxlelimitedslipdifferentialDifferentiallock() {
        return rearaxlelimitedslipdifferentialDifferentiallock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_configuration.RearAxleLimitedSlipDifferential_differentialLock
     *
     * @param rearaxlelimitedslipdifferentialDifferentiallock the value for control_configuration.RearAxleLimitedSlipDifferential_differentialLock
     *
     * @mbg.generated
     */
    public void setRearaxlelimitedslipdifferentialDifferentiallock(String rearaxlelimitedslipdifferentialDifferentiallock) {
        this.rearaxlelimitedslipdifferentialDifferentiallock = rearaxlelimitedslipdifferentialDifferentiallock == null ? null : rearaxlelimitedslipdifferentialDifferentiallock.trim();
    }
}