package com.forum.model.entity;

public class Engine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.EngineModel
     *
     * @mbg.generated
     */
    private String enginemodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.displacement
     *
     * @mbg.generated
     */
    private String displacement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.AirIntakeForm
     *
     * @mbg.generated
     */
    private String airintakeform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.CylinderArrangement
     *
     * @mbg.generated
     */
    private String cylinderarrangement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.NumberOfCylinders
     *
     * @mbg.generated
     */
    private String numberofcylinders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.NumberOfValvesPerCylinder
     *
     * @mbg.generated
     */
    private String numberofvalvespercylinder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.CompressionRatio
     *
     * @mbg.generated
     */
    private String compressionratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.DistributionAgency
     *
     * @mbg.generated
     */
    private String distributionagency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.TheCylinderDiameter
     *
     * @mbg.generated
     */
    private String thecylinderdiameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.trip
     *
     * @mbg.generated
     */
    private String trip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.MaximumHorsepower
     *
     * @mbg.generated
     */
    private String maximumhorsepower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.MaximumPower
     *
     * @mbg.generated
     */
    private String maximumpower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.MaximumPowerRpm
     *
     * @mbg.generated
     */
    private String maximumpowerrpm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.MaximumN_m
     *
     * @mbg.generated
     */
    private String maximumn_m;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.MaximumRpm
     *
     * @mbg.generated
     */
    private String maximumrpm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.CVVT
     *
     * @mbg.generated
     */
    private String cvvt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.FuelForm
     *
     * @mbg.generated
     */
    private String fuelform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.FuelLabel
     *
     * @mbg.generated
     */
    private String fuellabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.OilSupplyWay
     *
     * @mbg.generated
     */
    private String oilsupplyway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.CylinderHeadMaterial
     *
     * @mbg.generated
     */
    private String cylinderheadmaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.CylinderBodyMaterial
     *
     * @mbg.generated
     */
    private String cylinderbodymaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engine.EnvironmentalProtectionStandard
     *
     * @mbg.generated
     */
    private String environmentalprotectionstandard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.Num
     *
     * @return the value of engine.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.Num
     *
     * @param num the value for engine.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.EngineModel
     *
     * @return the value of engine.EngineModel
     *
     * @mbg.generated
     */
    public String getEnginemodel() {
        return enginemodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.EngineModel
     *
     * @param enginemodel the value for engine.EngineModel
     *
     * @mbg.generated
     */
    public void setEnginemodel(String enginemodel) {
        this.enginemodel = enginemodel == null ? null : enginemodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.displacement
     *
     * @return the value of engine.displacement
     *
     * @mbg.generated
     */
    public String getDisplacement() {
        return displacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.displacement
     *
     * @param displacement the value for engine.displacement
     *
     * @mbg.generated
     */
    public void setDisplacement(String displacement) {
        this.displacement = displacement == null ? null : displacement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.AirIntakeForm
     *
     * @return the value of engine.AirIntakeForm
     *
     * @mbg.generated
     */
    public String getAirintakeform() {
        return airintakeform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.AirIntakeForm
     *
     * @param airintakeform the value for engine.AirIntakeForm
     *
     * @mbg.generated
     */
    public void setAirintakeform(String airintakeform) {
        this.airintakeform = airintakeform == null ? null : airintakeform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.CylinderArrangement
     *
     * @return the value of engine.CylinderArrangement
     *
     * @mbg.generated
     */
    public String getCylinderarrangement() {
        return cylinderarrangement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.CylinderArrangement
     *
     * @param cylinderarrangement the value for engine.CylinderArrangement
     *
     * @mbg.generated
     */
    public void setCylinderarrangement(String cylinderarrangement) {
        this.cylinderarrangement = cylinderarrangement == null ? null : cylinderarrangement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.NumberOfCylinders
     *
     * @return the value of engine.NumberOfCylinders
     *
     * @mbg.generated
     */
    public String getNumberofcylinders() {
        return numberofcylinders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.NumberOfCylinders
     *
     * @param numberofcylinders the value for engine.NumberOfCylinders
     *
     * @mbg.generated
     */
    public void setNumberofcylinders(String numberofcylinders) {
        this.numberofcylinders = numberofcylinders == null ? null : numberofcylinders.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.NumberOfValvesPerCylinder
     *
     * @return the value of engine.NumberOfValvesPerCylinder
     *
     * @mbg.generated
     */
    public String getNumberofvalvespercylinder() {
        return numberofvalvespercylinder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.NumberOfValvesPerCylinder
     *
     * @param numberofvalvespercylinder the value for engine.NumberOfValvesPerCylinder
     *
     * @mbg.generated
     */
    public void setNumberofvalvespercylinder(String numberofvalvespercylinder) {
        this.numberofvalvespercylinder = numberofvalvespercylinder == null ? null : numberofvalvespercylinder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.CompressionRatio
     *
     * @return the value of engine.CompressionRatio
     *
     * @mbg.generated
     */
    public String getCompressionratio() {
        return compressionratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.CompressionRatio
     *
     * @param compressionratio the value for engine.CompressionRatio
     *
     * @mbg.generated
     */
    public void setCompressionratio(String compressionratio) {
        this.compressionratio = compressionratio == null ? null : compressionratio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.DistributionAgency
     *
     * @return the value of engine.DistributionAgency
     *
     * @mbg.generated
     */
    public String getDistributionagency() {
        return distributionagency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.DistributionAgency
     *
     * @param distributionagency the value for engine.DistributionAgency
     *
     * @mbg.generated
     */
    public void setDistributionagency(String distributionagency) {
        this.distributionagency = distributionagency == null ? null : distributionagency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.TheCylinderDiameter
     *
     * @return the value of engine.TheCylinderDiameter
     *
     * @mbg.generated
     */
    public String getThecylinderdiameter() {
        return thecylinderdiameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.TheCylinderDiameter
     *
     * @param thecylinderdiameter the value for engine.TheCylinderDiameter
     *
     * @mbg.generated
     */
    public void setThecylinderdiameter(String thecylinderdiameter) {
        this.thecylinderdiameter = thecylinderdiameter == null ? null : thecylinderdiameter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.trip
     *
     * @return the value of engine.trip
     *
     * @mbg.generated
     */
    public String getTrip() {
        return trip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.trip
     *
     * @param trip the value for engine.trip
     *
     * @mbg.generated
     */
    public void setTrip(String trip) {
        this.trip = trip == null ? null : trip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.MaximumHorsepower
     *
     * @return the value of engine.MaximumHorsepower
     *
     * @mbg.generated
     */
    public String getMaximumhorsepower() {
        return maximumhorsepower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.MaximumHorsepower
     *
     * @param maximumhorsepower the value for engine.MaximumHorsepower
     *
     * @mbg.generated
     */
    public void setMaximumhorsepower(String maximumhorsepower) {
        this.maximumhorsepower = maximumhorsepower == null ? null : maximumhorsepower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.MaximumPower
     *
     * @return the value of engine.MaximumPower
     *
     * @mbg.generated
     */
    public String getMaximumpower() {
        return maximumpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.MaximumPower
     *
     * @param maximumpower the value for engine.MaximumPower
     *
     * @mbg.generated
     */
    public void setMaximumpower(String maximumpower) {
        this.maximumpower = maximumpower == null ? null : maximumpower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.MaximumPowerRpm
     *
     * @return the value of engine.MaximumPowerRpm
     *
     * @mbg.generated
     */
    public String getMaximumpowerrpm() {
        return maximumpowerrpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.MaximumPowerRpm
     *
     * @param maximumpowerrpm the value for engine.MaximumPowerRpm
     *
     * @mbg.generated
     */
    public void setMaximumpowerrpm(String maximumpowerrpm) {
        this.maximumpowerrpm = maximumpowerrpm == null ? null : maximumpowerrpm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.MaximumN_m
     *
     * @return the value of engine.MaximumN_m
     *
     * @mbg.generated
     */
    public String getMaximumn_m() {
        return maximumn_m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.MaximumN_m
     *
     * @param maximumn_m the value for engine.MaximumN_m
     *
     * @mbg.generated
     */
    public void setMaximumn_m(String maximumn_m) {
        this.maximumn_m = maximumn_m == null ? null : maximumn_m.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.MaximumRpm
     *
     * @return the value of engine.MaximumRpm
     *
     * @mbg.generated
     */
    public String getMaximumrpm() {
        return maximumrpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.MaximumRpm
     *
     * @param maximumrpm the value for engine.MaximumRpm
     *
     * @mbg.generated
     */
    public void setMaximumrpm(String maximumrpm) {
        this.maximumrpm = maximumrpm == null ? null : maximumrpm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.CVVT
     *
     * @return the value of engine.CVVT
     *
     * @mbg.generated
     */
    public String getCvvt() {
        return cvvt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.CVVT
     *
     * @param cvvt the value for engine.CVVT
     *
     * @mbg.generated
     */
    public void setCvvt(String cvvt) {
        this.cvvt = cvvt == null ? null : cvvt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.FuelForm
     *
     * @return the value of engine.FuelForm
     *
     * @mbg.generated
     */
    public String getFuelform() {
        return fuelform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.FuelForm
     *
     * @param fuelform the value for engine.FuelForm
     *
     * @mbg.generated
     */
    public void setFuelform(String fuelform) {
        this.fuelform = fuelform == null ? null : fuelform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.FuelLabel
     *
     * @return the value of engine.FuelLabel
     *
     * @mbg.generated
     */
    public String getFuellabel() {
        return fuellabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.FuelLabel
     *
     * @param fuellabel the value for engine.FuelLabel
     *
     * @mbg.generated
     */
    public void setFuellabel(String fuellabel) {
        this.fuellabel = fuellabel == null ? null : fuellabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.OilSupplyWay
     *
     * @return the value of engine.OilSupplyWay
     *
     * @mbg.generated
     */
    public String getOilsupplyway() {
        return oilsupplyway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.OilSupplyWay
     *
     * @param oilsupplyway the value for engine.OilSupplyWay
     *
     * @mbg.generated
     */
    public void setOilsupplyway(String oilsupplyway) {
        this.oilsupplyway = oilsupplyway == null ? null : oilsupplyway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.CylinderHeadMaterial
     *
     * @return the value of engine.CylinderHeadMaterial
     *
     * @mbg.generated
     */
    public String getCylinderheadmaterial() {
        return cylinderheadmaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.CylinderHeadMaterial
     *
     * @param cylinderheadmaterial the value for engine.CylinderHeadMaterial
     *
     * @mbg.generated
     */
    public void setCylinderheadmaterial(String cylinderheadmaterial) {
        this.cylinderheadmaterial = cylinderheadmaterial == null ? null : cylinderheadmaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.CylinderBodyMaterial
     *
     * @return the value of engine.CylinderBodyMaterial
     *
     * @mbg.generated
     */
    public String getCylinderbodymaterial() {
        return cylinderbodymaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.CylinderBodyMaterial
     *
     * @param cylinderbodymaterial the value for engine.CylinderBodyMaterial
     *
     * @mbg.generated
     */
    public void setCylinderbodymaterial(String cylinderbodymaterial) {
        this.cylinderbodymaterial = cylinderbodymaterial == null ? null : cylinderbodymaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engine.EnvironmentalProtectionStandard
     *
     * @return the value of engine.EnvironmentalProtectionStandard
     *
     * @mbg.generated
     */
    public String getEnvironmentalprotectionstandard() {
        return environmentalprotectionstandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engine.EnvironmentalProtectionStandard
     *
     * @param environmentalprotectionstandard the value for engine.EnvironmentalProtectionStandard
     *
     * @mbg.generated
     */
    public void setEnvironmentalprotectionstandard(String environmentalprotectionstandard) {
        this.environmentalprotectionstandard = environmentalprotectionstandard == null ? null : environmentalprotectionstandard.trim();
    }
}