package com.forum.model.entity;

public class External_configuration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column external_configuration.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column external_configuration.PowerSunroof
     *
     * @mbg.generated
     */
    private String powersunroof;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column external_configuration.PanoramicSunroof
     *
     * @mbg.generated
     */
    private String panoramicsunroof;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column external_configuration.SportsAppearanceSuite
     *
     * @mbg.generated
     */
    private String sportsappearancesuite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column external_configuration.AluminiumAlloyRim
     *
     * @mbg.generated
     */
    private String aluminiumalloyrim;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column external_configuration.ElectricSuctionDoor
     *
     * @mbg.generated
     */
    private String electricsuctiondoor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column external_configuration.SlidingDoor
     *
     * @mbg.generated
     */
    private String slidingdoor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column external_configuration.ElectricTrunk
     *
     * @mbg.generated
     */
    private String electrictrunk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column external_configuration.InductionTrunk
     *
     * @mbg.generated
     */
    private String inductiontrunk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column external_configuration.RoofRack
     *
     * @mbg.generated
     */
    private String roofrack;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column external_configuration.Num
     *
     * @return the value of external_configuration.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column external_configuration.Num
     *
     * @param num the value for external_configuration.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column external_configuration.PowerSunroof
     *
     * @return the value of external_configuration.PowerSunroof
     *
     * @mbg.generated
     */
    public String getPowersunroof() {
        return powersunroof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column external_configuration.PowerSunroof
     *
     * @param powersunroof the value for external_configuration.PowerSunroof
     *
     * @mbg.generated
     */
    public void setPowersunroof(String powersunroof) {
        this.powersunroof = powersunroof == null ? null : powersunroof.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column external_configuration.PanoramicSunroof
     *
     * @return the value of external_configuration.PanoramicSunroof
     *
     * @mbg.generated
     */
    public String getPanoramicsunroof() {
        return panoramicsunroof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column external_configuration.PanoramicSunroof
     *
     * @param panoramicsunroof the value for external_configuration.PanoramicSunroof
     *
     * @mbg.generated
     */
    public void setPanoramicsunroof(String panoramicsunroof) {
        this.panoramicsunroof = panoramicsunroof == null ? null : panoramicsunroof.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column external_configuration.SportsAppearanceSuite
     *
     * @return the value of external_configuration.SportsAppearanceSuite
     *
     * @mbg.generated
     */
    public String getSportsappearancesuite() {
        return sportsappearancesuite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column external_configuration.SportsAppearanceSuite
     *
     * @param sportsappearancesuite the value for external_configuration.SportsAppearanceSuite
     *
     * @mbg.generated
     */
    public void setSportsappearancesuite(String sportsappearancesuite) {
        this.sportsappearancesuite = sportsappearancesuite == null ? null : sportsappearancesuite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column external_configuration.AluminiumAlloyRim
     *
     * @return the value of external_configuration.AluminiumAlloyRim
     *
     * @mbg.generated
     */
    public String getAluminiumalloyrim() {
        return aluminiumalloyrim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column external_configuration.AluminiumAlloyRim
     *
     * @param aluminiumalloyrim the value for external_configuration.AluminiumAlloyRim
     *
     * @mbg.generated
     */
    public void setAluminiumalloyrim(String aluminiumalloyrim) {
        this.aluminiumalloyrim = aluminiumalloyrim == null ? null : aluminiumalloyrim.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column external_configuration.ElectricSuctionDoor
     *
     * @return the value of external_configuration.ElectricSuctionDoor
     *
     * @mbg.generated
     */
    public String getElectricsuctiondoor() {
        return electricsuctiondoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column external_configuration.ElectricSuctionDoor
     *
     * @param electricsuctiondoor the value for external_configuration.ElectricSuctionDoor
     *
     * @mbg.generated
     */
    public void setElectricsuctiondoor(String electricsuctiondoor) {
        this.electricsuctiondoor = electricsuctiondoor == null ? null : electricsuctiondoor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column external_configuration.SlidingDoor
     *
     * @return the value of external_configuration.SlidingDoor
     *
     * @mbg.generated
     */
    public String getSlidingdoor() {
        return slidingdoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column external_configuration.SlidingDoor
     *
     * @param slidingdoor the value for external_configuration.SlidingDoor
     *
     * @mbg.generated
     */
    public void setSlidingdoor(String slidingdoor) {
        this.slidingdoor = slidingdoor == null ? null : slidingdoor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column external_configuration.ElectricTrunk
     *
     * @return the value of external_configuration.ElectricTrunk
     *
     * @mbg.generated
     */
    public String getElectrictrunk() {
        return electrictrunk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column external_configuration.ElectricTrunk
     *
     * @param electrictrunk the value for external_configuration.ElectricTrunk
     *
     * @mbg.generated
     */
    public void setElectrictrunk(String electrictrunk) {
        this.electrictrunk = electrictrunk == null ? null : electrictrunk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column external_configuration.InductionTrunk
     *
     * @return the value of external_configuration.InductionTrunk
     *
     * @mbg.generated
     */
    public String getInductiontrunk() {
        return inductiontrunk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column external_configuration.InductionTrunk
     *
     * @param inductiontrunk the value for external_configuration.InductionTrunk
     *
     * @mbg.generated
     */
    public void setInductiontrunk(String inductiontrunk) {
        this.inductiontrunk = inductiontrunk == null ? null : inductiontrunk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column external_configuration.RoofRack
     *
     * @return the value of external_configuration.RoofRack
     *
     * @mbg.generated
     */
    public String getRoofrack() {
        return roofrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column external_configuration.RoofRack
     *
     * @param roofrack the value for external_configuration.RoofRack
     *
     * @mbg.generated
     */
    public void setRoofrack(String roofrack) {
        this.roofrack = roofrack == null ? null : roofrack.trim();
    }
}