package com.forum.model.entity;

public class Glass_rearviewmirror {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.Front_rearPowerWindows
     *
     * @mbg.generated
     */
    private String frontRearpowerwindows;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.CarWindowAnti_pinchFunction
     *
     * @mbg.generated
     */
    private String carwindowantiPinchfunction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.Uv_heatResistantGlass
     *
     * @mbg.generated
     */
    private String uvHeatresistantglass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.TheRearViewMirrorElectricallyAdjusted
     *
     * @mbg.generated
     */
    private String therearviewmirrorelectricallyadjusted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.RearviewMirrorHeated
     *
     * @mbg.generated
     */
    private String rearviewmirrorheated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.Inner_outerRearviewMirrorAutomaticallyPreventsGlare
     *
     * @mbg.generated
     */
    private String innerOuterrearviewmirrorautomaticallypreventsglare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.TheEearviewMirrorFoldsElectrically
     *
     * @mbg.generated
     */
    private String theeearviewmirrorfoldselectrically;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.RearviewMirrorMemory
     *
     * @mbg.generated
     */
    private String rearviewmirrormemory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.RearWindscreenShade
     *
     * @mbg.generated
     */
    private String rearwindscreenshade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.RearSideShade
     *
     * @mbg.generated
     */
    private String rearsideshade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.RearPrivacyGlass
     *
     * @mbg.generated
     */
    private String rearprivacyglass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.SunSisorMirror
     *
     * @mbg.generated
     */
    private String sunsisormirror;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.RearWiper
     *
     * @mbg.generated
     */
    private String rearwiper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column glass_rearviewmirror.Rain_sensingWipers
     *
     * @mbg.generated
     */
    private String rainSensingwipers;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.Num
     *
     * @return the value of glass_rearviewmirror.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.Num
     *
     * @param num the value for glass_rearviewmirror.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.Front_rearPowerWindows
     *
     * @return the value of glass_rearviewmirror.Front_rearPowerWindows
     *
     * @mbg.generated
     */
    public String getFrontRearpowerwindows() {
        return frontRearpowerwindows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.Front_rearPowerWindows
     *
     * @param frontRearpowerwindows the value for glass_rearviewmirror.Front_rearPowerWindows
     *
     * @mbg.generated
     */
    public void setFrontRearpowerwindows(String frontRearpowerwindows) {
        this.frontRearpowerwindows = frontRearpowerwindows == null ? null : frontRearpowerwindows.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.CarWindowAnti_pinchFunction
     *
     * @return the value of glass_rearviewmirror.CarWindowAnti_pinchFunction
     *
     * @mbg.generated
     */
    public String getCarwindowantiPinchfunction() {
        return carwindowantiPinchfunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.CarWindowAnti_pinchFunction
     *
     * @param carwindowantiPinchfunction the value for glass_rearviewmirror.CarWindowAnti_pinchFunction
     *
     * @mbg.generated
     */
    public void setCarwindowantiPinchfunction(String carwindowantiPinchfunction) {
        this.carwindowantiPinchfunction = carwindowantiPinchfunction == null ? null : carwindowantiPinchfunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.Uv_heatResistantGlass
     *
     * @return the value of glass_rearviewmirror.Uv_heatResistantGlass
     *
     * @mbg.generated
     */
    public String getUvHeatresistantglass() {
        return uvHeatresistantglass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.Uv_heatResistantGlass
     *
     * @param uvHeatresistantglass the value for glass_rearviewmirror.Uv_heatResistantGlass
     *
     * @mbg.generated
     */
    public void setUvHeatresistantglass(String uvHeatresistantglass) {
        this.uvHeatresistantglass = uvHeatresistantglass == null ? null : uvHeatresistantglass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.TheRearViewMirrorElectricallyAdjusted
     *
     * @return the value of glass_rearviewmirror.TheRearViewMirrorElectricallyAdjusted
     *
     * @mbg.generated
     */
    public String getTherearviewmirrorelectricallyadjusted() {
        return therearviewmirrorelectricallyadjusted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.TheRearViewMirrorElectricallyAdjusted
     *
     * @param therearviewmirrorelectricallyadjusted the value for glass_rearviewmirror.TheRearViewMirrorElectricallyAdjusted
     *
     * @mbg.generated
     */
    public void setTherearviewmirrorelectricallyadjusted(String therearviewmirrorelectricallyadjusted) {
        this.therearviewmirrorelectricallyadjusted = therearviewmirrorelectricallyadjusted == null ? null : therearviewmirrorelectricallyadjusted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.RearviewMirrorHeated
     *
     * @return the value of glass_rearviewmirror.RearviewMirrorHeated
     *
     * @mbg.generated
     */
    public String getRearviewmirrorheated() {
        return rearviewmirrorheated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.RearviewMirrorHeated
     *
     * @param rearviewmirrorheated the value for glass_rearviewmirror.RearviewMirrorHeated
     *
     * @mbg.generated
     */
    public void setRearviewmirrorheated(String rearviewmirrorheated) {
        this.rearviewmirrorheated = rearviewmirrorheated == null ? null : rearviewmirrorheated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.Inner_outerRearviewMirrorAutomaticallyPreventsGlare
     *
     * @return the value of glass_rearviewmirror.Inner_outerRearviewMirrorAutomaticallyPreventsGlare
     *
     * @mbg.generated
     */
    public String getInnerOuterrearviewmirrorautomaticallypreventsglare() {
        return innerOuterrearviewmirrorautomaticallypreventsglare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.Inner_outerRearviewMirrorAutomaticallyPreventsGlare
     *
     * @param innerOuterrearviewmirrorautomaticallypreventsglare the value for glass_rearviewmirror.Inner_outerRearviewMirrorAutomaticallyPreventsGlare
     *
     * @mbg.generated
     */
    public void setInnerOuterrearviewmirrorautomaticallypreventsglare(String innerOuterrearviewmirrorautomaticallypreventsglare) {
        this.innerOuterrearviewmirrorautomaticallypreventsglare = innerOuterrearviewmirrorautomaticallypreventsglare == null ? null : innerOuterrearviewmirrorautomaticallypreventsglare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.TheEearviewMirrorFoldsElectrically
     *
     * @return the value of glass_rearviewmirror.TheEearviewMirrorFoldsElectrically
     *
     * @mbg.generated
     */
    public String getTheeearviewmirrorfoldselectrically() {
        return theeearviewmirrorfoldselectrically;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.TheEearviewMirrorFoldsElectrically
     *
     * @param theeearviewmirrorfoldselectrically the value for glass_rearviewmirror.TheEearviewMirrorFoldsElectrically
     *
     * @mbg.generated
     */
    public void setTheeearviewmirrorfoldselectrically(String theeearviewmirrorfoldselectrically) {
        this.theeearviewmirrorfoldselectrically = theeearviewmirrorfoldselectrically == null ? null : theeearviewmirrorfoldselectrically.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.RearviewMirrorMemory
     *
     * @return the value of glass_rearviewmirror.RearviewMirrorMemory
     *
     * @mbg.generated
     */
    public String getRearviewmirrormemory() {
        return rearviewmirrormemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.RearviewMirrorMemory
     *
     * @param rearviewmirrormemory the value for glass_rearviewmirror.RearviewMirrorMemory
     *
     * @mbg.generated
     */
    public void setRearviewmirrormemory(String rearviewmirrormemory) {
        this.rearviewmirrormemory = rearviewmirrormemory == null ? null : rearviewmirrormemory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.RearWindscreenShade
     *
     * @return the value of glass_rearviewmirror.RearWindscreenShade
     *
     * @mbg.generated
     */
    public String getRearwindscreenshade() {
        return rearwindscreenshade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.RearWindscreenShade
     *
     * @param rearwindscreenshade the value for glass_rearviewmirror.RearWindscreenShade
     *
     * @mbg.generated
     */
    public void setRearwindscreenshade(String rearwindscreenshade) {
        this.rearwindscreenshade = rearwindscreenshade == null ? null : rearwindscreenshade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.RearSideShade
     *
     * @return the value of glass_rearviewmirror.RearSideShade
     *
     * @mbg.generated
     */
    public String getRearsideshade() {
        return rearsideshade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.RearSideShade
     *
     * @param rearsideshade the value for glass_rearviewmirror.RearSideShade
     *
     * @mbg.generated
     */
    public void setRearsideshade(String rearsideshade) {
        this.rearsideshade = rearsideshade == null ? null : rearsideshade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.RearPrivacyGlass
     *
     * @return the value of glass_rearviewmirror.RearPrivacyGlass
     *
     * @mbg.generated
     */
    public String getRearprivacyglass() {
        return rearprivacyglass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.RearPrivacyGlass
     *
     * @param rearprivacyglass the value for glass_rearviewmirror.RearPrivacyGlass
     *
     * @mbg.generated
     */
    public void setRearprivacyglass(String rearprivacyglass) {
        this.rearprivacyglass = rearprivacyglass == null ? null : rearprivacyglass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.SunSisorMirror
     *
     * @return the value of glass_rearviewmirror.SunSisorMirror
     *
     * @mbg.generated
     */
    public String getSunsisormirror() {
        return sunsisormirror;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.SunSisorMirror
     *
     * @param sunsisormirror the value for glass_rearviewmirror.SunSisorMirror
     *
     * @mbg.generated
     */
    public void setSunsisormirror(String sunsisormirror) {
        this.sunsisormirror = sunsisormirror == null ? null : sunsisormirror.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.RearWiper
     *
     * @return the value of glass_rearviewmirror.RearWiper
     *
     * @mbg.generated
     */
    public String getRearwiper() {
        return rearwiper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.RearWiper
     *
     * @param rearwiper the value for glass_rearviewmirror.RearWiper
     *
     * @mbg.generated
     */
    public void setRearwiper(String rearwiper) {
        this.rearwiper = rearwiper == null ? null : rearwiper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column glass_rearviewmirror.Rain_sensingWipers
     *
     * @return the value of glass_rearviewmirror.Rain_sensingWipers
     *
     * @mbg.generated
     */
    public String getRainSensingwipers() {
        return rainSensingwipers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column glass_rearviewmirror.Rain_sensingWipers
     *
     * @param rainSensingwipers the value for glass_rearviewmirror.Rain_sensingWipers
     *
     * @mbg.generated
     */
    public void setRainSensingwipers(String rainSensingwipers) {
        this.rainSensingwipers = rainSensingwipers == null ? null : rainSensingwipers.trim();
    }
}