package com.forum.model.entity;

public class High_tech_configuration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_tech_configuration.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_tech_configuration.AutomaticParking
     *
     * @mbg.generated
     */
    private String automaticparking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_tech_configuration.GSG
     *
     * @mbg.generated
     */
    private String gsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_tech_configuration.DoublingTheAuxiliary
     *
     * @mbg.generated
     */
    private String doublingtheauxiliary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_tech_configuration.LDWS
     *
     * @mbg.generated
     */
    private String ldws;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_tech_configuration.ActiveBrake_ActiveSafetySystem
     *
     * @mbg.generated
     */
    private String activebrakeActivesafetysystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_tech_configuration.IntegralActiveSteering
     *
     * @mbg.generated
     */
    private String integralactivesteering;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_tech_configuration.NightCisionSystem
     *
     * @mbg.generated
     */
    private String nightcisionsystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_tech_configuration.CentralControlLCDSplitScreenDisplay
     *
     * @mbg.generated
     */
    private String centralcontrollcdsplitscreendisplay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_tech_configuration.Self_adaptiveCruiseControl
     *
     * @mbg.generated
     */
    private String selfAdaptivecruisecontrol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column high_tech_configuration.PanoramicCamera
     *
     * @mbg.generated
     */
    private String panoramiccamera;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_tech_configuration.Num
     *
     * @return the value of high_tech_configuration.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_tech_configuration.Num
     *
     * @param num the value for high_tech_configuration.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_tech_configuration.AutomaticParking
     *
     * @return the value of high_tech_configuration.AutomaticParking
     *
     * @mbg.generated
     */
    public String getAutomaticparking() {
        return automaticparking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_tech_configuration.AutomaticParking
     *
     * @param automaticparking the value for high_tech_configuration.AutomaticParking
     *
     * @mbg.generated
     */
    public void setAutomaticparking(String automaticparking) {
        this.automaticparking = automaticparking == null ? null : automaticparking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_tech_configuration.GSG
     *
     * @return the value of high_tech_configuration.GSG
     *
     * @mbg.generated
     */
    public String getGsg() {
        return gsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_tech_configuration.GSG
     *
     * @param gsg the value for high_tech_configuration.GSG
     *
     * @mbg.generated
     */
    public void setGsg(String gsg) {
        this.gsg = gsg == null ? null : gsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_tech_configuration.DoublingTheAuxiliary
     *
     * @return the value of high_tech_configuration.DoublingTheAuxiliary
     *
     * @mbg.generated
     */
    public String getDoublingtheauxiliary() {
        return doublingtheauxiliary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_tech_configuration.DoublingTheAuxiliary
     *
     * @param doublingtheauxiliary the value for high_tech_configuration.DoublingTheAuxiliary
     *
     * @mbg.generated
     */
    public void setDoublingtheauxiliary(String doublingtheauxiliary) {
        this.doublingtheauxiliary = doublingtheauxiliary == null ? null : doublingtheauxiliary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_tech_configuration.LDWS
     *
     * @return the value of high_tech_configuration.LDWS
     *
     * @mbg.generated
     */
    public String getLdws() {
        return ldws;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_tech_configuration.LDWS
     *
     * @param ldws the value for high_tech_configuration.LDWS
     *
     * @mbg.generated
     */
    public void setLdws(String ldws) {
        this.ldws = ldws == null ? null : ldws.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_tech_configuration.ActiveBrake_ActiveSafetySystem
     *
     * @return the value of high_tech_configuration.ActiveBrake_ActiveSafetySystem
     *
     * @mbg.generated
     */
    public String getActivebrakeActivesafetysystem() {
        return activebrakeActivesafetysystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_tech_configuration.ActiveBrake_ActiveSafetySystem
     *
     * @param activebrakeActivesafetysystem the value for high_tech_configuration.ActiveBrake_ActiveSafetySystem
     *
     * @mbg.generated
     */
    public void setActivebrakeActivesafetysystem(String activebrakeActivesafetysystem) {
        this.activebrakeActivesafetysystem = activebrakeActivesafetysystem == null ? null : activebrakeActivesafetysystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_tech_configuration.IntegralActiveSteering
     *
     * @return the value of high_tech_configuration.IntegralActiveSteering
     *
     * @mbg.generated
     */
    public String getIntegralactivesteering() {
        return integralactivesteering;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_tech_configuration.IntegralActiveSteering
     *
     * @param integralactivesteering the value for high_tech_configuration.IntegralActiveSteering
     *
     * @mbg.generated
     */
    public void setIntegralactivesteering(String integralactivesteering) {
        this.integralactivesteering = integralactivesteering == null ? null : integralactivesteering.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_tech_configuration.NightCisionSystem
     *
     * @return the value of high_tech_configuration.NightCisionSystem
     *
     * @mbg.generated
     */
    public String getNightcisionsystem() {
        return nightcisionsystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_tech_configuration.NightCisionSystem
     *
     * @param nightcisionsystem the value for high_tech_configuration.NightCisionSystem
     *
     * @mbg.generated
     */
    public void setNightcisionsystem(String nightcisionsystem) {
        this.nightcisionsystem = nightcisionsystem == null ? null : nightcisionsystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_tech_configuration.CentralControlLCDSplitScreenDisplay
     *
     * @return the value of high_tech_configuration.CentralControlLCDSplitScreenDisplay
     *
     * @mbg.generated
     */
    public String getCentralcontrollcdsplitscreendisplay() {
        return centralcontrollcdsplitscreendisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_tech_configuration.CentralControlLCDSplitScreenDisplay
     *
     * @param centralcontrollcdsplitscreendisplay the value for high_tech_configuration.CentralControlLCDSplitScreenDisplay
     *
     * @mbg.generated
     */
    public void setCentralcontrollcdsplitscreendisplay(String centralcontrollcdsplitscreendisplay) {
        this.centralcontrollcdsplitscreendisplay = centralcontrollcdsplitscreendisplay == null ? null : centralcontrollcdsplitscreendisplay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_tech_configuration.Self_adaptiveCruiseControl
     *
     * @return the value of high_tech_configuration.Self_adaptiveCruiseControl
     *
     * @mbg.generated
     */
    public String getSelfAdaptivecruisecontrol() {
        return selfAdaptivecruisecontrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_tech_configuration.Self_adaptiveCruiseControl
     *
     * @param selfAdaptivecruisecontrol the value for high_tech_configuration.Self_adaptiveCruiseControl
     *
     * @mbg.generated
     */
    public void setSelfAdaptivecruisecontrol(String selfAdaptivecruisecontrol) {
        this.selfAdaptivecruisecontrol = selfAdaptivecruisecontrol == null ? null : selfAdaptivecruisecontrol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column high_tech_configuration.PanoramicCamera
     *
     * @return the value of high_tech_configuration.PanoramicCamera
     *
     * @mbg.generated
     */
    public String getPanoramiccamera() {
        return panoramiccamera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column high_tech_configuration.PanoramicCamera
     *
     * @param panoramiccamera the value for high_tech_configuration.PanoramicCamera
     *
     * @mbg.generated
     */
    public void setPanoramiccamera(String panoramiccamera) {
        this.panoramiccamera = panoramiccamera == null ? null : panoramiccamera.trim();
    }
}