package com.forum.model.entity;

public class Internal_configuration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.LeatherSteeringWheel
     *
     * @mbg.generated
     */
    private String leathersteeringwheel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.SteeringWheelControl
     *
     * @mbg.generated
     */
    private String steeringwheelcontrol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.ElectricSteeringWheelControl
     *
     * @mbg.generated
     */
    private String electricsteeringwheelcontrol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.MFL
     *
     * @mbg.generated
     */
    private String mfl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.SteeringWheelShift
     *
     * @mbg.generated
     */
    private String steeringwheelshift;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.HeatedSteeringWheel
     *
     * @mbg.generated
     */
    private String heatedsteeringwheel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.SteeringMemory
     *
     * @mbg.generated
     */
    private String steeringmemory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.Cruise
     *
     * @mbg.generated
     */
    private String cruise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.Front_rearParkingRadar
     *
     * @mbg.generated
     */
    private String frontRearparkingradar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.RearVideo
     *
     * @mbg.generated
     */
    private String rearvideo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.DrivingComputerDisplayScreen
     *
     * @mbg.generated
     */
    private String drivingcomputerdisplayscreen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.FullLCDPanel
     *
     * @mbg.generated
     */
    private String fulllcdpanel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internal_configuration.HUD
     *
     * @mbg.generated
     */
    private String hud;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.Num
     *
     * @return the value of internal_configuration.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.Num
     *
     * @param num the value for internal_configuration.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.LeatherSteeringWheel
     *
     * @return the value of internal_configuration.LeatherSteeringWheel
     *
     * @mbg.generated
     */
    public String getLeathersteeringwheel() {
        return leathersteeringwheel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.LeatherSteeringWheel
     *
     * @param leathersteeringwheel the value for internal_configuration.LeatherSteeringWheel
     *
     * @mbg.generated
     */
    public void setLeathersteeringwheel(String leathersteeringwheel) {
        this.leathersteeringwheel = leathersteeringwheel == null ? null : leathersteeringwheel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.SteeringWheelControl
     *
     * @return the value of internal_configuration.SteeringWheelControl
     *
     * @mbg.generated
     */
    public String getSteeringwheelcontrol() {
        return steeringwheelcontrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.SteeringWheelControl
     *
     * @param steeringwheelcontrol the value for internal_configuration.SteeringWheelControl
     *
     * @mbg.generated
     */
    public void setSteeringwheelcontrol(String steeringwheelcontrol) {
        this.steeringwheelcontrol = steeringwheelcontrol == null ? null : steeringwheelcontrol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.ElectricSteeringWheelControl
     *
     * @return the value of internal_configuration.ElectricSteeringWheelControl
     *
     * @mbg.generated
     */
    public String getElectricsteeringwheelcontrol() {
        return electricsteeringwheelcontrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.ElectricSteeringWheelControl
     *
     * @param electricsteeringwheelcontrol the value for internal_configuration.ElectricSteeringWheelControl
     *
     * @mbg.generated
     */
    public void setElectricsteeringwheelcontrol(String electricsteeringwheelcontrol) {
        this.electricsteeringwheelcontrol = electricsteeringwheelcontrol == null ? null : electricsteeringwheelcontrol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.MFL
     *
     * @return the value of internal_configuration.MFL
     *
     * @mbg.generated
     */
    public String getMfl() {
        return mfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.MFL
     *
     * @param mfl the value for internal_configuration.MFL
     *
     * @mbg.generated
     */
    public void setMfl(String mfl) {
        this.mfl = mfl == null ? null : mfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.SteeringWheelShift
     *
     * @return the value of internal_configuration.SteeringWheelShift
     *
     * @mbg.generated
     */
    public String getSteeringwheelshift() {
        return steeringwheelshift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.SteeringWheelShift
     *
     * @param steeringwheelshift the value for internal_configuration.SteeringWheelShift
     *
     * @mbg.generated
     */
    public void setSteeringwheelshift(String steeringwheelshift) {
        this.steeringwheelshift = steeringwheelshift == null ? null : steeringwheelshift.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.HeatedSteeringWheel
     *
     * @return the value of internal_configuration.HeatedSteeringWheel
     *
     * @mbg.generated
     */
    public String getHeatedsteeringwheel() {
        return heatedsteeringwheel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.HeatedSteeringWheel
     *
     * @param heatedsteeringwheel the value for internal_configuration.HeatedSteeringWheel
     *
     * @mbg.generated
     */
    public void setHeatedsteeringwheel(String heatedsteeringwheel) {
        this.heatedsteeringwheel = heatedsteeringwheel == null ? null : heatedsteeringwheel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.SteeringMemory
     *
     * @return the value of internal_configuration.SteeringMemory
     *
     * @mbg.generated
     */
    public String getSteeringmemory() {
        return steeringmemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.SteeringMemory
     *
     * @param steeringmemory the value for internal_configuration.SteeringMemory
     *
     * @mbg.generated
     */
    public void setSteeringmemory(String steeringmemory) {
        this.steeringmemory = steeringmemory == null ? null : steeringmemory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.Cruise
     *
     * @return the value of internal_configuration.Cruise
     *
     * @mbg.generated
     */
    public String getCruise() {
        return cruise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.Cruise
     *
     * @param cruise the value for internal_configuration.Cruise
     *
     * @mbg.generated
     */
    public void setCruise(String cruise) {
        this.cruise = cruise == null ? null : cruise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.Front_rearParkingRadar
     *
     * @return the value of internal_configuration.Front_rearParkingRadar
     *
     * @mbg.generated
     */
    public String getFrontRearparkingradar() {
        return frontRearparkingradar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.Front_rearParkingRadar
     *
     * @param frontRearparkingradar the value for internal_configuration.Front_rearParkingRadar
     *
     * @mbg.generated
     */
    public void setFrontRearparkingradar(String frontRearparkingradar) {
        this.frontRearparkingradar = frontRearparkingradar == null ? null : frontRearparkingradar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.RearVideo
     *
     * @return the value of internal_configuration.RearVideo
     *
     * @mbg.generated
     */
    public String getRearvideo() {
        return rearvideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.RearVideo
     *
     * @param rearvideo the value for internal_configuration.RearVideo
     *
     * @mbg.generated
     */
    public void setRearvideo(String rearvideo) {
        this.rearvideo = rearvideo == null ? null : rearvideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.DrivingComputerDisplayScreen
     *
     * @return the value of internal_configuration.DrivingComputerDisplayScreen
     *
     * @mbg.generated
     */
    public String getDrivingcomputerdisplayscreen() {
        return drivingcomputerdisplayscreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.DrivingComputerDisplayScreen
     *
     * @param drivingcomputerdisplayscreen the value for internal_configuration.DrivingComputerDisplayScreen
     *
     * @mbg.generated
     */
    public void setDrivingcomputerdisplayscreen(String drivingcomputerdisplayscreen) {
        this.drivingcomputerdisplayscreen = drivingcomputerdisplayscreen == null ? null : drivingcomputerdisplayscreen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.FullLCDPanel
     *
     * @return the value of internal_configuration.FullLCDPanel
     *
     * @mbg.generated
     */
    public String getFulllcdpanel() {
        return fulllcdpanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.FullLCDPanel
     *
     * @param fulllcdpanel the value for internal_configuration.FullLCDPanel
     *
     * @mbg.generated
     */
    public void setFulllcdpanel(String fulllcdpanel) {
        this.fulllcdpanel = fulllcdpanel == null ? null : fulllcdpanel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internal_configuration.HUD
     *
     * @return the value of internal_configuration.HUD
     *
     * @mbg.generated
     */
    public String getHud() {
        return hud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internal_configuration.HUD
     *
     * @param hud the value for internal_configuration.HUD
     *
     * @mbg.generated
     */
    public void setHud(String hud) {
        this.hud = hud == null ? null : hud.trim();
    }
}