package com.forum.model.entity;

public class Light_configuration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_configuration.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_configuration.DippedHeadlight
     *
     * @mbg.generated
     */
    private String dippedheadlight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_configuration.HighBeam
     *
     * @mbg.generated
     */
    private String highbeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_configuration.DaytimeRunningLight
     *
     * @mbg.generated
     */
    private String daytimerunninglight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_configuration.AdaptiveToNearAndFarLight
     *
     * @mbg.generated
     */
    private String adaptivetonearandfarlight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_configuration.AutoLight
     *
     * @mbg.generated
     */
    private String autolight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_configuration.CorneringLamp
     *
     * @mbg.generated
     */
    private String corneringlamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_configuration.SteeringHeadLamp
     *
     * @mbg.generated
     */
    private String steeringheadlamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_configuration.FrontFogLamp
     *
     * @mbg.generated
     */
    private String frontfoglamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_configuration.TheHeadlampHeightIsAdjustable
     *
     * @mbg.generated
     */
    private String theheadlampheightisadjustable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_configuration.HeadlampCleaningDevice
     *
     * @mbg.generated
     */
    private String headlampcleaningdevice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_configuration.InteriorAtmosphereLamp
     *
     * @mbg.generated
     */
    private String interioratmospherelamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_configuration.Num
     *
     * @return the value of light_configuration.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_configuration.Num
     *
     * @param num the value for light_configuration.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_configuration.DippedHeadlight
     *
     * @return the value of light_configuration.DippedHeadlight
     *
     * @mbg.generated
     */
    public String getDippedheadlight() {
        return dippedheadlight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_configuration.DippedHeadlight
     *
     * @param dippedheadlight the value for light_configuration.DippedHeadlight
     *
     * @mbg.generated
     */
    public void setDippedheadlight(String dippedheadlight) {
        this.dippedheadlight = dippedheadlight == null ? null : dippedheadlight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_configuration.HighBeam
     *
     * @return the value of light_configuration.HighBeam
     *
     * @mbg.generated
     */
    public String getHighbeam() {
        return highbeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_configuration.HighBeam
     *
     * @param highbeam the value for light_configuration.HighBeam
     *
     * @mbg.generated
     */
    public void setHighbeam(String highbeam) {
        this.highbeam = highbeam == null ? null : highbeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_configuration.DaytimeRunningLight
     *
     * @return the value of light_configuration.DaytimeRunningLight
     *
     * @mbg.generated
     */
    public String getDaytimerunninglight() {
        return daytimerunninglight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_configuration.DaytimeRunningLight
     *
     * @param daytimerunninglight the value for light_configuration.DaytimeRunningLight
     *
     * @mbg.generated
     */
    public void setDaytimerunninglight(String daytimerunninglight) {
        this.daytimerunninglight = daytimerunninglight == null ? null : daytimerunninglight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_configuration.AdaptiveToNearAndFarLight
     *
     * @return the value of light_configuration.AdaptiveToNearAndFarLight
     *
     * @mbg.generated
     */
    public String getAdaptivetonearandfarlight() {
        return adaptivetonearandfarlight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_configuration.AdaptiveToNearAndFarLight
     *
     * @param adaptivetonearandfarlight the value for light_configuration.AdaptiveToNearAndFarLight
     *
     * @mbg.generated
     */
    public void setAdaptivetonearandfarlight(String adaptivetonearandfarlight) {
        this.adaptivetonearandfarlight = adaptivetonearandfarlight == null ? null : adaptivetonearandfarlight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_configuration.AutoLight
     *
     * @return the value of light_configuration.AutoLight
     *
     * @mbg.generated
     */
    public String getAutolight() {
        return autolight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_configuration.AutoLight
     *
     * @param autolight the value for light_configuration.AutoLight
     *
     * @mbg.generated
     */
    public void setAutolight(String autolight) {
        this.autolight = autolight == null ? null : autolight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_configuration.CorneringLamp
     *
     * @return the value of light_configuration.CorneringLamp
     *
     * @mbg.generated
     */
    public String getCorneringlamp() {
        return corneringlamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_configuration.CorneringLamp
     *
     * @param corneringlamp the value for light_configuration.CorneringLamp
     *
     * @mbg.generated
     */
    public void setCorneringlamp(String corneringlamp) {
        this.corneringlamp = corneringlamp == null ? null : corneringlamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_configuration.SteeringHeadLamp
     *
     * @return the value of light_configuration.SteeringHeadLamp
     *
     * @mbg.generated
     */
    public String getSteeringheadlamp() {
        return steeringheadlamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_configuration.SteeringHeadLamp
     *
     * @param steeringheadlamp the value for light_configuration.SteeringHeadLamp
     *
     * @mbg.generated
     */
    public void setSteeringheadlamp(String steeringheadlamp) {
        this.steeringheadlamp = steeringheadlamp == null ? null : steeringheadlamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_configuration.FrontFogLamp
     *
     * @return the value of light_configuration.FrontFogLamp
     *
     * @mbg.generated
     */
    public String getFrontfoglamp() {
        return frontfoglamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_configuration.FrontFogLamp
     *
     * @param frontfoglamp the value for light_configuration.FrontFogLamp
     *
     * @mbg.generated
     */
    public void setFrontfoglamp(String frontfoglamp) {
        this.frontfoglamp = frontfoglamp == null ? null : frontfoglamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_configuration.TheHeadlampHeightIsAdjustable
     *
     * @return the value of light_configuration.TheHeadlampHeightIsAdjustable
     *
     * @mbg.generated
     */
    public String getTheheadlampheightisadjustable() {
        return theheadlampheightisadjustable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_configuration.TheHeadlampHeightIsAdjustable
     *
     * @param theheadlampheightisadjustable the value for light_configuration.TheHeadlampHeightIsAdjustable
     *
     * @mbg.generated
     */
    public void setTheheadlampheightisadjustable(String theheadlampheightisadjustable) {
        this.theheadlampheightisadjustable = theheadlampheightisadjustable == null ? null : theheadlampheightisadjustable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_configuration.HeadlampCleaningDevice
     *
     * @return the value of light_configuration.HeadlampCleaningDevice
     *
     * @mbg.generated
     */
    public String getHeadlampcleaningdevice() {
        return headlampcleaningdevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_configuration.HeadlampCleaningDevice
     *
     * @param headlampcleaningdevice the value for light_configuration.HeadlampCleaningDevice
     *
     * @mbg.generated
     */
    public void setHeadlampcleaningdevice(String headlampcleaningdevice) {
        this.headlampcleaningdevice = headlampcleaningdevice == null ? null : headlampcleaningdevice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_configuration.InteriorAtmosphereLamp
     *
     * @return the value of light_configuration.InteriorAtmosphereLamp
     *
     * @mbg.generated
     */
    public String getInterioratmospherelamp() {
        return interioratmospherelamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_configuration.InteriorAtmosphereLamp
     *
     * @param interioratmospherelamp the value for light_configuration.InteriorAtmosphereLamp
     *
     * @mbg.generated
     */
    public void setInterioratmospherelamp(String interioratmospherelamp) {
        this.interioratmospherelamp = interioratmospherelamp == null ? null : interioratmospherelamp.trim();
    }
}