package com.forum.model.entity;

public class Media_configuration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.GPS
     *
     * @mbg.generated
     */
    private String gps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.LocationInteractiveService
     *
     * @mbg.generated
     */
    private String locationinteractiveservice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.CenterConsoleLargeColorScreen
     *
     * @mbg.generated
     */
    private String centerconsolelargecolorscreen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.Bluetooth_carPhone
     *
     * @mbg.generated
     */
    private String bluetoothCarphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.TV
     *
     * @mbg.generated
     */
    private String tv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.RearLCD
     *
     * @mbg.generated
     */
    private String rearlcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.powersupply220v230v
     *
     * @mbg.generated
     */
    private String powersupply220v230v;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.ExternalAudioSourceInterface
     *
     * @mbg.generated
     */
    private String externalaudiosourceinterface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.CD
     *
     * @mbg.generated
     */
    private String cd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.MediaSystem
     *
     * @mbg.generated
     */
    private String mediasystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.Dynaudio
     *
     * @mbg.generated
     */
    private String dynaudio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column media_configuration.NumberOfSpeakers
     *
     * @mbg.generated
     */
    private String numberofspeakers;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.Num
     *
     * @return the value of media_configuration.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.Num
     *
     * @param num the value for media_configuration.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.GPS
     *
     * @return the value of media_configuration.GPS
     *
     * @mbg.generated
     */
    public String getGps() {
        return gps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.GPS
     *
     * @param gps the value for media_configuration.GPS
     *
     * @mbg.generated
     */
    public void setGps(String gps) {
        this.gps = gps == null ? null : gps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.LocationInteractiveService
     *
     * @return the value of media_configuration.LocationInteractiveService
     *
     * @mbg.generated
     */
    public String getLocationinteractiveservice() {
        return locationinteractiveservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.LocationInteractiveService
     *
     * @param locationinteractiveservice the value for media_configuration.LocationInteractiveService
     *
     * @mbg.generated
     */
    public void setLocationinteractiveservice(String locationinteractiveservice) {
        this.locationinteractiveservice = locationinteractiveservice == null ? null : locationinteractiveservice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.CenterConsoleLargeColorScreen
     *
     * @return the value of media_configuration.CenterConsoleLargeColorScreen
     *
     * @mbg.generated
     */
    public String getCenterconsolelargecolorscreen() {
        return centerconsolelargecolorscreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.CenterConsoleLargeColorScreen
     *
     * @param centerconsolelargecolorscreen the value for media_configuration.CenterConsoleLargeColorScreen
     *
     * @mbg.generated
     */
    public void setCenterconsolelargecolorscreen(String centerconsolelargecolorscreen) {
        this.centerconsolelargecolorscreen = centerconsolelargecolorscreen == null ? null : centerconsolelargecolorscreen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.Bluetooth_carPhone
     *
     * @return the value of media_configuration.Bluetooth_carPhone
     *
     * @mbg.generated
     */
    public String getBluetoothCarphone() {
        return bluetoothCarphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.Bluetooth_carPhone
     *
     * @param bluetoothCarphone the value for media_configuration.Bluetooth_carPhone
     *
     * @mbg.generated
     */
    public void setBluetoothCarphone(String bluetoothCarphone) {
        this.bluetoothCarphone = bluetoothCarphone == null ? null : bluetoothCarphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.TV
     *
     * @return the value of media_configuration.TV
     *
     * @mbg.generated
     */
    public String getTv() {
        return tv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.TV
     *
     * @param tv the value for media_configuration.TV
     *
     * @mbg.generated
     */
    public void setTv(String tv) {
        this.tv = tv == null ? null : tv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.RearLCD
     *
     * @return the value of media_configuration.RearLCD
     *
     * @mbg.generated
     */
    public String getRearlcd() {
        return rearlcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.RearLCD
     *
     * @param rearlcd the value for media_configuration.RearLCD
     *
     * @mbg.generated
     */
    public void setRearlcd(String rearlcd) {
        this.rearlcd = rearlcd == null ? null : rearlcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.powersupply220v230v
     *
     * @return the value of media_configuration.powersupply220v230v
     *
     * @mbg.generated
     */
    public String getPowersupply220v230v() {
        return powersupply220v230v;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.powersupply220v230v
     *
     * @param powersupply220v230v the value for media_configuration.powersupply220v230v
     *
     * @mbg.generated
     */
    public void setPowersupply220v230v(String powersupply220v230v) {
        this.powersupply220v230v = powersupply220v230v == null ? null : powersupply220v230v.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.ExternalAudioSourceInterface
     *
     * @return the value of media_configuration.ExternalAudioSourceInterface
     *
     * @mbg.generated
     */
    public String getExternalaudiosourceinterface() {
        return externalaudiosourceinterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.ExternalAudioSourceInterface
     *
     * @param externalaudiosourceinterface the value for media_configuration.ExternalAudioSourceInterface
     *
     * @mbg.generated
     */
    public void setExternalaudiosourceinterface(String externalaudiosourceinterface) {
        this.externalaudiosourceinterface = externalaudiosourceinterface == null ? null : externalaudiosourceinterface.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.CD
     *
     * @return the value of media_configuration.CD
     *
     * @mbg.generated
     */
    public String getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.CD
     *
     * @param cd the value for media_configuration.CD
     *
     * @mbg.generated
     */
    public void setCd(String cd) {
        this.cd = cd == null ? null : cd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.MediaSystem
     *
     * @return the value of media_configuration.MediaSystem
     *
     * @mbg.generated
     */
    public String getMediasystem() {
        return mediasystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.MediaSystem
     *
     * @param mediasystem the value for media_configuration.MediaSystem
     *
     * @mbg.generated
     */
    public void setMediasystem(String mediasystem) {
        this.mediasystem = mediasystem == null ? null : mediasystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.Dynaudio
     *
     * @return the value of media_configuration.Dynaudio
     *
     * @mbg.generated
     */
    public String getDynaudio() {
        return dynaudio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.Dynaudio
     *
     * @param dynaudio the value for media_configuration.Dynaudio
     *
     * @mbg.generated
     */
    public void setDynaudio(String dynaudio) {
        this.dynaudio = dynaudio == null ? null : dynaudio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media_configuration.NumberOfSpeakers
     *
     * @return the value of media_configuration.NumberOfSpeakers
     *
     * @mbg.generated
     */
    public String getNumberofspeakers() {
        return numberofspeakers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media_configuration.NumberOfSpeakers
     *
     * @param numberofspeakers the value for media_configuration.NumberOfSpeakers
     *
     * @mbg.generated
     */
    public void setNumberofspeakers(String numberofspeakers) {
        this.numberofspeakers = numberofspeakers == null ? null : numberofspeakers.trim();
    }
}