package com.forum.model.entity;

public class Safety_equipment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.Main_SecondaryAirbag
     *
     * @mbg.generated
     */
    private String mainSecondaryairbag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.Front_BackSideAirbag
     *
     * @mbg.generated
     */
    private String frontBacksideairbag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.Front_BackHeadAirbag
     *
     * @mbg.generated
     */
    private String frontBackheadairbag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.KneeAirbag
     *
     * @mbg.generated
     */
    private String kneeairbag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.TirePressureMonitoringDevice
     *
     * @mbg.generated
     */
    private String tirepressuremonitoringdevice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.ZerotirePressureToContinueDriving
     *
     * @mbg.generated
     */
    private String zerotirepressuretocontinuedriving;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.SeatBeltWarning
     *
     * @mbg.generated
     */
    private String seatbeltwarning;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.ISOFIX
     *
     * @mbg.generated
     */
    private String isofix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.EMMO
     *
     * @mbg.generated
     */
    private String emmo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.CentralLock
     *
     * @mbg.generated
     */
    private String centrallock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.RemoteKey
     *
     * @mbg.generated
     */
    private String remotekey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.PEPS
     *
     * @mbg.generated
     */
    private String peps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column safety_equipment.PKE
     *
     * @mbg.generated
     */
    private String pke;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.Num
     *
     * @return the value of safety_equipment.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.Num
     *
     * @param num the value for safety_equipment.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.Main_SecondaryAirbag
     *
     * @return the value of safety_equipment.Main_SecondaryAirbag
     *
     * @mbg.generated
     */
    public String getMainSecondaryairbag() {
        return mainSecondaryairbag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.Main_SecondaryAirbag
     *
     * @param mainSecondaryairbag the value for safety_equipment.Main_SecondaryAirbag
     *
     * @mbg.generated
     */
    public void setMainSecondaryairbag(String mainSecondaryairbag) {
        this.mainSecondaryairbag = mainSecondaryairbag == null ? null : mainSecondaryairbag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.Front_BackSideAirbag
     *
     * @return the value of safety_equipment.Front_BackSideAirbag
     *
     * @mbg.generated
     */
    public String getFrontBacksideairbag() {
        return frontBacksideairbag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.Front_BackSideAirbag
     *
     * @param frontBacksideairbag the value for safety_equipment.Front_BackSideAirbag
     *
     * @mbg.generated
     */
    public void setFrontBacksideairbag(String frontBacksideairbag) {
        this.frontBacksideairbag = frontBacksideairbag == null ? null : frontBacksideairbag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.Front_BackHeadAirbag
     *
     * @return the value of safety_equipment.Front_BackHeadAirbag
     *
     * @mbg.generated
     */
    public String getFrontBackheadairbag() {
        return frontBackheadairbag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.Front_BackHeadAirbag
     *
     * @param frontBackheadairbag the value for safety_equipment.Front_BackHeadAirbag
     *
     * @mbg.generated
     */
    public void setFrontBackheadairbag(String frontBackheadairbag) {
        this.frontBackheadairbag = frontBackheadairbag == null ? null : frontBackheadairbag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.KneeAirbag
     *
     * @return the value of safety_equipment.KneeAirbag
     *
     * @mbg.generated
     */
    public String getKneeairbag() {
        return kneeairbag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.KneeAirbag
     *
     * @param kneeairbag the value for safety_equipment.KneeAirbag
     *
     * @mbg.generated
     */
    public void setKneeairbag(String kneeairbag) {
        this.kneeairbag = kneeairbag == null ? null : kneeairbag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.TirePressureMonitoringDevice
     *
     * @return the value of safety_equipment.TirePressureMonitoringDevice
     *
     * @mbg.generated
     */
    public String getTirepressuremonitoringdevice() {
        return tirepressuremonitoringdevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.TirePressureMonitoringDevice
     *
     * @param tirepressuremonitoringdevice the value for safety_equipment.TirePressureMonitoringDevice
     *
     * @mbg.generated
     */
    public void setTirepressuremonitoringdevice(String tirepressuremonitoringdevice) {
        this.tirepressuremonitoringdevice = tirepressuremonitoringdevice == null ? null : tirepressuremonitoringdevice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.ZerotirePressureToContinueDriving
     *
     * @return the value of safety_equipment.ZerotirePressureToContinueDriving
     *
     * @mbg.generated
     */
    public String getZerotirepressuretocontinuedriving() {
        return zerotirepressuretocontinuedriving;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.ZerotirePressureToContinueDriving
     *
     * @param zerotirepressuretocontinuedriving the value for safety_equipment.ZerotirePressureToContinueDriving
     *
     * @mbg.generated
     */
    public void setZerotirepressuretocontinuedriving(String zerotirepressuretocontinuedriving) {
        this.zerotirepressuretocontinuedriving = zerotirepressuretocontinuedriving == null ? null : zerotirepressuretocontinuedriving.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.SeatBeltWarning
     *
     * @return the value of safety_equipment.SeatBeltWarning
     *
     * @mbg.generated
     */
    public String getSeatbeltwarning() {
        return seatbeltwarning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.SeatBeltWarning
     *
     * @param seatbeltwarning the value for safety_equipment.SeatBeltWarning
     *
     * @mbg.generated
     */
    public void setSeatbeltwarning(String seatbeltwarning) {
        this.seatbeltwarning = seatbeltwarning == null ? null : seatbeltwarning.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.ISOFIX
     *
     * @return the value of safety_equipment.ISOFIX
     *
     * @mbg.generated
     */
    public String getIsofix() {
        return isofix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.ISOFIX
     *
     * @param isofix the value for safety_equipment.ISOFIX
     *
     * @mbg.generated
     */
    public void setIsofix(String isofix) {
        this.isofix = isofix == null ? null : isofix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.EMMO
     *
     * @return the value of safety_equipment.EMMO
     *
     * @mbg.generated
     */
    public String getEmmo() {
        return emmo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.EMMO
     *
     * @param emmo the value for safety_equipment.EMMO
     *
     * @mbg.generated
     */
    public void setEmmo(String emmo) {
        this.emmo = emmo == null ? null : emmo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.CentralLock
     *
     * @return the value of safety_equipment.CentralLock
     *
     * @mbg.generated
     */
    public String getCentrallock() {
        return centrallock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.CentralLock
     *
     * @param centrallock the value for safety_equipment.CentralLock
     *
     * @mbg.generated
     */
    public void setCentrallock(String centrallock) {
        this.centrallock = centrallock == null ? null : centrallock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.RemoteKey
     *
     * @return the value of safety_equipment.RemoteKey
     *
     * @mbg.generated
     */
    public String getRemotekey() {
        return remotekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.RemoteKey
     *
     * @param remotekey the value for safety_equipment.RemoteKey
     *
     * @mbg.generated
     */
    public void setRemotekey(String remotekey) {
        this.remotekey = remotekey == null ? null : remotekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.PEPS
     *
     * @return the value of safety_equipment.PEPS
     *
     * @mbg.generated
     */
    public String getPeps() {
        return peps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.PEPS
     *
     * @param peps the value for safety_equipment.PEPS
     *
     * @mbg.generated
     */
    public void setPeps(String peps) {
        this.peps = peps == null ? null : peps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column safety_equipment.PKE
     *
     * @return the value of safety_equipment.PKE
     *
     * @mbg.generated
     */
    public String getPke() {
        return pke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column safety_equipment.PKE
     *
     * @param pke the value for safety_equipment.PKE
     *
     * @mbg.generated
     */
    public void setPke(String pke) {
        this.pke = pke == null ? null : pke.trim();
    }
}