package com.forum.model.entity;

public class Seat_configuration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.SeatMaterial
     *
     * @mbg.generated
     */
    private String seatmaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.SportsSeat
     *
     * @mbg.generated
     */
    private String sportsseat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.SeatHeightAdjustment
     *
     * @mbg.generated
     */
    private String seatheightadjustment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.LumbarSupportAdjustment
     *
     * @mbg.generated
     */
    private String lumbarsupportadjustment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.ShoulderSupportAdjustment
     *
     * @mbg.generated
     */
    private String shouldersupportadjustment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.Main_passengerSeatElectricAdjustment
     *
     * @mbg.generated
     */
    private String mainPassengerseatelectricadjustment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.AdjustTheBackAngleOfTheSecondRow
     *
     * @mbg.generated
     */
    private String adjustthebackangleofthesecondrow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.TheSecondRowOfSeatsMoves
     *
     * @mbg.generated
     */
    private String thesecondrowofseatsmoves;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.RearSeatElectricallyAdjusted
     *
     * @mbg.generated
     */
    private String rearseatelectricallyadjusted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.ElectrionicSeatMemory
     *
     * @mbg.generated
     */
    private String electrionicseatmemory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.Front_rearSeatsHeated
     *
     * @mbg.generated
     */
    private String frontRearseatsheated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.Front_rearSeatVentilation
     *
     * @mbg.generated
     */
    private String frontRearseatventilation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.Front_backSeatMassage
     *
     * @mbg.generated
     */
    private String frontBackseatmassage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.ThirdRowSeat
     *
     * @mbg.generated
     */
    private String thirdrowseat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.BackSeatUpsideDownMode
     *
     * @mbg.generated
     */
    private String backseatupsidedownmode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.Front_rearCenterHandrail
     *
     * @mbg.generated
     */
    private String frontRearcenterhandrail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat_configuration.TheRearStand
     *
     * @mbg.generated
     */
    private String therearstand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.Num
     *
     * @return the value of seat_configuration.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.Num
     *
     * @param num the value for seat_configuration.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.SeatMaterial
     *
     * @return the value of seat_configuration.SeatMaterial
     *
     * @mbg.generated
     */
    public String getSeatmaterial() {
        return seatmaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.SeatMaterial
     *
     * @param seatmaterial the value for seat_configuration.SeatMaterial
     *
     * @mbg.generated
     */
    public void setSeatmaterial(String seatmaterial) {
        this.seatmaterial = seatmaterial == null ? null : seatmaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.SportsSeat
     *
     * @return the value of seat_configuration.SportsSeat
     *
     * @mbg.generated
     */
    public String getSportsseat() {
        return sportsseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.SportsSeat
     *
     * @param sportsseat the value for seat_configuration.SportsSeat
     *
     * @mbg.generated
     */
    public void setSportsseat(String sportsseat) {
        this.sportsseat = sportsseat == null ? null : sportsseat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.SeatHeightAdjustment
     *
     * @return the value of seat_configuration.SeatHeightAdjustment
     *
     * @mbg.generated
     */
    public String getSeatheightadjustment() {
        return seatheightadjustment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.SeatHeightAdjustment
     *
     * @param seatheightadjustment the value for seat_configuration.SeatHeightAdjustment
     *
     * @mbg.generated
     */
    public void setSeatheightadjustment(String seatheightadjustment) {
        this.seatheightadjustment = seatheightadjustment == null ? null : seatheightadjustment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.LumbarSupportAdjustment
     *
     * @return the value of seat_configuration.LumbarSupportAdjustment
     *
     * @mbg.generated
     */
    public String getLumbarsupportadjustment() {
        return lumbarsupportadjustment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.LumbarSupportAdjustment
     *
     * @param lumbarsupportadjustment the value for seat_configuration.LumbarSupportAdjustment
     *
     * @mbg.generated
     */
    public void setLumbarsupportadjustment(String lumbarsupportadjustment) {
        this.lumbarsupportadjustment = lumbarsupportadjustment == null ? null : lumbarsupportadjustment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.ShoulderSupportAdjustment
     *
     * @return the value of seat_configuration.ShoulderSupportAdjustment
     *
     * @mbg.generated
     */
    public String getShouldersupportadjustment() {
        return shouldersupportadjustment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.ShoulderSupportAdjustment
     *
     * @param shouldersupportadjustment the value for seat_configuration.ShoulderSupportAdjustment
     *
     * @mbg.generated
     */
    public void setShouldersupportadjustment(String shouldersupportadjustment) {
        this.shouldersupportadjustment = shouldersupportadjustment == null ? null : shouldersupportadjustment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.Main_passengerSeatElectricAdjustment
     *
     * @return the value of seat_configuration.Main_passengerSeatElectricAdjustment
     *
     * @mbg.generated
     */
    public String getMainPassengerseatelectricadjustment() {
        return mainPassengerseatelectricadjustment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.Main_passengerSeatElectricAdjustment
     *
     * @param mainPassengerseatelectricadjustment the value for seat_configuration.Main_passengerSeatElectricAdjustment
     *
     * @mbg.generated
     */
    public void setMainPassengerseatelectricadjustment(String mainPassengerseatelectricadjustment) {
        this.mainPassengerseatelectricadjustment = mainPassengerseatelectricadjustment == null ? null : mainPassengerseatelectricadjustment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.AdjustTheBackAngleOfTheSecondRow
     *
     * @return the value of seat_configuration.AdjustTheBackAngleOfTheSecondRow
     *
     * @mbg.generated
     */
    public String getAdjustthebackangleofthesecondrow() {
        return adjustthebackangleofthesecondrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.AdjustTheBackAngleOfTheSecondRow
     *
     * @param adjustthebackangleofthesecondrow the value for seat_configuration.AdjustTheBackAngleOfTheSecondRow
     *
     * @mbg.generated
     */
    public void setAdjustthebackangleofthesecondrow(String adjustthebackangleofthesecondrow) {
        this.adjustthebackangleofthesecondrow = adjustthebackangleofthesecondrow == null ? null : adjustthebackangleofthesecondrow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.TheSecondRowOfSeatsMoves
     *
     * @return the value of seat_configuration.TheSecondRowOfSeatsMoves
     *
     * @mbg.generated
     */
    public String getThesecondrowofseatsmoves() {
        return thesecondrowofseatsmoves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.TheSecondRowOfSeatsMoves
     *
     * @param thesecondrowofseatsmoves the value for seat_configuration.TheSecondRowOfSeatsMoves
     *
     * @mbg.generated
     */
    public void setThesecondrowofseatsmoves(String thesecondrowofseatsmoves) {
        this.thesecondrowofseatsmoves = thesecondrowofseatsmoves == null ? null : thesecondrowofseatsmoves.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.RearSeatElectricallyAdjusted
     *
     * @return the value of seat_configuration.RearSeatElectricallyAdjusted
     *
     * @mbg.generated
     */
    public String getRearseatelectricallyadjusted() {
        return rearseatelectricallyadjusted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.RearSeatElectricallyAdjusted
     *
     * @param rearseatelectricallyadjusted the value for seat_configuration.RearSeatElectricallyAdjusted
     *
     * @mbg.generated
     */
    public void setRearseatelectricallyadjusted(String rearseatelectricallyadjusted) {
        this.rearseatelectricallyadjusted = rearseatelectricallyadjusted == null ? null : rearseatelectricallyadjusted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.ElectrionicSeatMemory
     *
     * @return the value of seat_configuration.ElectrionicSeatMemory
     *
     * @mbg.generated
     */
    public String getElectrionicseatmemory() {
        return electrionicseatmemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.ElectrionicSeatMemory
     *
     * @param electrionicseatmemory the value for seat_configuration.ElectrionicSeatMemory
     *
     * @mbg.generated
     */
    public void setElectrionicseatmemory(String electrionicseatmemory) {
        this.electrionicseatmemory = electrionicseatmemory == null ? null : electrionicseatmemory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.Front_rearSeatsHeated
     *
     * @return the value of seat_configuration.Front_rearSeatsHeated
     *
     * @mbg.generated
     */
    public String getFrontRearseatsheated() {
        return frontRearseatsheated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.Front_rearSeatsHeated
     *
     * @param frontRearseatsheated the value for seat_configuration.Front_rearSeatsHeated
     *
     * @mbg.generated
     */
    public void setFrontRearseatsheated(String frontRearseatsheated) {
        this.frontRearseatsheated = frontRearseatsheated == null ? null : frontRearseatsheated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.Front_rearSeatVentilation
     *
     * @return the value of seat_configuration.Front_rearSeatVentilation
     *
     * @mbg.generated
     */
    public String getFrontRearseatventilation() {
        return frontRearseatventilation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.Front_rearSeatVentilation
     *
     * @param frontRearseatventilation the value for seat_configuration.Front_rearSeatVentilation
     *
     * @mbg.generated
     */
    public void setFrontRearseatventilation(String frontRearseatventilation) {
        this.frontRearseatventilation = frontRearseatventilation == null ? null : frontRearseatventilation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.Front_backSeatMassage
     *
     * @return the value of seat_configuration.Front_backSeatMassage
     *
     * @mbg.generated
     */
    public String getFrontBackseatmassage() {
        return frontBackseatmassage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.Front_backSeatMassage
     *
     * @param frontBackseatmassage the value for seat_configuration.Front_backSeatMassage
     *
     * @mbg.generated
     */
    public void setFrontBackseatmassage(String frontBackseatmassage) {
        this.frontBackseatmassage = frontBackseatmassage == null ? null : frontBackseatmassage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.ThirdRowSeat
     *
     * @return the value of seat_configuration.ThirdRowSeat
     *
     * @mbg.generated
     */
    public String getThirdrowseat() {
        return thirdrowseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.ThirdRowSeat
     *
     * @param thirdrowseat the value for seat_configuration.ThirdRowSeat
     *
     * @mbg.generated
     */
    public void setThirdrowseat(String thirdrowseat) {
        this.thirdrowseat = thirdrowseat == null ? null : thirdrowseat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.BackSeatUpsideDownMode
     *
     * @return the value of seat_configuration.BackSeatUpsideDownMode
     *
     * @mbg.generated
     */
    public String getBackseatupsidedownmode() {
        return backseatupsidedownmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.BackSeatUpsideDownMode
     *
     * @param backseatupsidedownmode the value for seat_configuration.BackSeatUpsideDownMode
     *
     * @mbg.generated
     */
    public void setBackseatupsidedownmode(String backseatupsidedownmode) {
        this.backseatupsidedownmode = backseatupsidedownmode == null ? null : backseatupsidedownmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.Front_rearCenterHandrail
     *
     * @return the value of seat_configuration.Front_rearCenterHandrail
     *
     * @mbg.generated
     */
    public String getFrontRearcenterhandrail() {
        return frontRearcenterhandrail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.Front_rearCenterHandrail
     *
     * @param frontRearcenterhandrail the value for seat_configuration.Front_rearCenterHandrail
     *
     * @mbg.generated
     */
    public void setFrontRearcenterhandrail(String frontRearcenterhandrail) {
        this.frontRearcenterhandrail = frontRearcenterhandrail == null ? null : frontRearcenterhandrail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat_configuration.TheRearStand
     *
     * @return the value of seat_configuration.TheRearStand
     *
     * @mbg.generated
     */
    public String getTherearstand() {
        return therearstand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat_configuration.TheRearStand
     *
     * @param therearstand the value for seat_configuration.TheRearStand
     *
     * @mbg.generated
     */
    public void setTherearstand(String therearstand) {
        this.therearstand = therearstand == null ? null : therearstand.trim();
    }
}