package com.forum.model.entity;

public class Wheel_brake {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wheel_brake.Num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wheel_brake.FrontBrakeType
     *
     * @mbg.generated
     */
    private String frontbraketype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wheel_brake.RearBrakeType
     *
     * @mbg.generated
     */
    private String rearbraketype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wheel_brake.ParkingBrakeType
     *
     * @mbg.generated
     */
    private String parkingbraketype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wheel_brake.FrontTireType
     *
     * @mbg.generated
     */
    private String fronttiretype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wheel_brake.RearTireType
     *
     * @mbg.generated
     */
    private String reartiretype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wheel_brake.SpareTireType
     *
     * @mbg.generated
     */
    private String sparetiretype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wheel_brake.Num
     *
     * @return the value of wheel_brake.Num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wheel_brake.Num
     *
     * @param num the value for wheel_brake.Num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wheel_brake.FrontBrakeType
     *
     * @return the value of wheel_brake.FrontBrakeType
     *
     * @mbg.generated
     */
    public String getFrontbraketype() {
        return frontbraketype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wheel_brake.FrontBrakeType
     *
     * @param frontbraketype the value for wheel_brake.FrontBrakeType
     *
     * @mbg.generated
     */
    public void setFrontbraketype(String frontbraketype) {
        this.frontbraketype = frontbraketype == null ? null : frontbraketype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wheel_brake.RearBrakeType
     *
     * @return the value of wheel_brake.RearBrakeType
     *
     * @mbg.generated
     */
    public String getRearbraketype() {
        return rearbraketype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wheel_brake.RearBrakeType
     *
     * @param rearbraketype the value for wheel_brake.RearBrakeType
     *
     * @mbg.generated
     */
    public void setRearbraketype(String rearbraketype) {
        this.rearbraketype = rearbraketype == null ? null : rearbraketype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wheel_brake.ParkingBrakeType
     *
     * @return the value of wheel_brake.ParkingBrakeType
     *
     * @mbg.generated
     */
    public String getParkingbraketype() {
        return parkingbraketype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wheel_brake.ParkingBrakeType
     *
     * @param parkingbraketype the value for wheel_brake.ParkingBrakeType
     *
     * @mbg.generated
     */
    public void setParkingbraketype(String parkingbraketype) {
        this.parkingbraketype = parkingbraketype == null ? null : parkingbraketype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wheel_brake.FrontTireType
     *
     * @return the value of wheel_brake.FrontTireType
     *
     * @mbg.generated
     */
    public String getFronttiretype() {
        return fronttiretype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wheel_brake.FrontTireType
     *
     * @param fronttiretype the value for wheel_brake.FrontTireType
     *
     * @mbg.generated
     */
    public void setFronttiretype(String fronttiretype) {
        this.fronttiretype = fronttiretype == null ? null : fronttiretype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wheel_brake.RearTireType
     *
     * @return the value of wheel_brake.RearTireType
     *
     * @mbg.generated
     */
    public String getReartiretype() {
        return reartiretype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wheel_brake.RearTireType
     *
     * @param reartiretype the value for wheel_brake.RearTireType
     *
     * @mbg.generated
     */
    public void setReartiretype(String reartiretype) {
        this.reartiretype = reartiretype == null ? null : reartiretype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wheel_brake.SpareTireType
     *
     * @return the value of wheel_brake.SpareTireType
     *
     * @mbg.generated
     */
    public String getSparetiretype() {
        return sparetiretype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wheel_brake.SpareTireType
     *
     * @param sparetiretype the value for wheel_brake.SpareTireType
     *
     * @mbg.generated
     */
    public void setSparetiretype(String sparetiretype) {
        this.sparetiretype = sparetiretype == null ? null : sparetiretype.trim();
    }
}